### ISSUE TITLE
Aggregate graphs (causes, services) pull answer codes instead of labels from ls

### ISSUE THREAD

**Issue by SamuelPetragallo** [WorldHealthOrganization/herams-backend#102]
![image](https://user-images.githubusercontent.com/15345099/55937302-ef0c5e80-5c38-11e9-92d9-837cf4845a29.png)

**Comment by SamMousa** [comment]
Aggregate graphs never pull labels, they have configurable labels in the via the chart settings.
For example, see this one:
https://herams.org/element/35/update

Having aggregate data pull labels from a (random / first / last) question is not intuitive and will. Instead specifying it the chart configuration will make it more predictable and easier to understand.

**Comment by SamuelPetragallo** [comment]
Just seeing that now - makes sense indeed
