### ISSUE TITLE
MOZ - Map not rendering due to invalid latitude

### ISSUE THREAD

**Issue by SamuelPetragallo** [WorldHealthOrganization/herams-backend#103]
Not sure what he issue is with the lat though - ?

Error reads: Rendering this element caused an error: Invalid latitude: -12.860345 for response r34iRTL(etc.). The most common reason for the error is an invalid question code in its configuration. You can edit the element here.

**Comment by SamMousa** [comment]
![image](https://user-images.githubusercontent.com/547021/55944393-cee49b80-5c48-11e9-9267-91fc28f4a1df.png)

This is why one should never use google summaries...
![image](https://user-images.githubusercontent.com/547021/55944420-dd32b780-5c48-11e9-8b04-13c6bbfb9989.png)


So currently we only allow positive coordinates, will fix that.

**Comment by SamuelPetragallo** [comment]
Great!
