### ISSUE TITLE
1/3 Measurement screens

### ISSUE THREAD

**Issue by be-novelt** [WorldHealthOrganization/herams-backend#105]
Hi, according with @SamuelPetragallo, see attached all the mesurement screens.
![HeRAMs_map_measures_2](https://user-images.githubusercontent.com/43411015/55974632-64535000-5c88-11e9-93f8-56af3b921149.jpg)
![HeRAMs_map_measures_3](https://user-images.githubusercontent.com/43411015/55974633-64ebe680-5c88-11e9-8c98-49b7a7ab3e03.jpg)
![HeRAMs_map_measures](https://user-images.githubusercontent.com/43411015/55974634-64ebe680-5c88-11e9-8f05-58ad12cb4bf0.jpg)

**Comment by SamMousa** [comment]
Sign up screen seems out of date, current form contains a lot less items
