### ISSUE TITLE
2/3 Graphic mockups

### ISSUE THREAD

**Issue by be-novelt** [WorldHealthOrganization/herams-backend#106]
Suite of the previous issue > a summary of all the graphic screens of Herams already sent.

![1 HeRAMs_admin](https://user-images.githubusercontent.com/43411015/55974775-b09e9000-5c88-11e9-9636-626d21d1458d.jpg)
![2 HeRAMs_adminHover](https://user-images.githubusercontent.com/43411015/55974780-b09e9000-5c88-11e9-9645-e8c23f696f9a.jpg)
![3 HeRAMs_admin_Project](https://user-images.githubusercontent.com/43411015/55974784-b09e9000-5c88-11e9-8047-8370ffb2417c.jpg)
![4 HeRAMs_admin_Project_search](https://user-images.githubusercontent.com/43411015/55974786-b09e9000-5c88-11e9-93bd-d697ccde0ec3.jpg)
![5 HeRAMs_admin_WorkspaceData](https://user-images.githubusercontent.com/43411015/55974788-b09e9000-5c88-11e9-89d5-f2aeb0e143a3.jpg)
![6 HeRAMs_admin_WorkspaceData_bis](https://user-images.githubusercontent.com/43411015/55974789-b1372680-5c88-11e9-8895-57adb3bb9604.jpg)
![7 HeRAMs_admin_WorkspaceSharing](https://user-images.githubusercontent.com/43411015/55974790-b1372680-5c88-11e9-831e-96ee9abbba9b.jpg)
![8 HeRAMs_admin_WorkspaceSettings](https://user-images.githubusercontent.com/43411015/55974792-b1372680-5c88-11e9-9a11-d912cf6605ba.jpg)
![9 HeRAMs_admin_WorkspaceData_EditUpdate](https://user-images.githubusercontent.com/43411015/55974793-b1372680-5c88-11e9-8fde-bf37b88a845d.jpg)
![10 HeRAMs_admin_WorkspaceData_EditUpdate_2](https://user-images.githubusercontent.com/43411015/55974794-b1cfbd00-5c88-11e9-9f90-bc9a5d1a4c3a.jpg)
![11 HeRAMs_admin_WorkspaceData_EditUpdate_Confirm](https://user-images.githubusercontent.com/43411015/55974795-b1cfbd00-5c88-11e9-92d4-c37515d7a16f.jpg)
![12 HeRAMs_admin_WorkspaceData_Create](https://user-images.githubusercontent.com/43411015/55974796-b1cfbd00-5c88-11e9-9530-8675a3d41d1f.jpg)
![Herams_ErrorPage_1](https://user-images.githubusercontent.com/43411015/55974846-d2981280-5c88-11e9-8c16-84c391e1c9d2.jpg)
![Herams_ErrorPage_2](https://user-images.githubusercontent.com/43411015/55974847-d2981280-5c88-11e9-8986-f1348325db47.jpg)
![Herams_ErrorPage](https://user-images.githubusercontent.com/43411015/55974849-d330a900-5c88-11e9-8f0e-0adbe9390472.jpg)
![HeRAMs_login_1](https://user-images.githubusercontent.com/43411015/55974877-eba0c380-5c88-11e9-8500-669000630414.jpg)
![HeRAMs_login_2](https://user-images.githubusercontent.com/43411015/55974879-eba0c380-5c88-11e9-890f-5070799d4f46.jpg)
![HeRAMs_login_3](https://user-images.githubusercontent.com/43411015/55974881-eba0c380-5c88-11e9-93be-e15d4ad30b96.jpg)
![HeRAMs_map_1](https://user-images.githubusercontent.com/43411015/55974882-eba0c380-5c88-11e9-8b5c-d9daa22f276e.jpg)
![HeRAMs_map_1bis](https://user-images.githubusercontent.com/43411015/55974884-eba0c380-5c88-11e9-8f0a-3cb18ce901b2.jpg)
![HeRAMs_map_2](https://user-images.githubusercontent.com/43411015/55974885-ec395a00-5c88-11e9-995d-bffb247f3878.jpg)
![HeRAMs_map_2bis](https://user-images.githubusercontent.com/43411015/55974886-ec395a00-5c88-11e9-9543-b9b3d37f2e88.jpg)

**Comment by SamMousa** [comment]
Closing this issue since it doesn't have a clearly scoped goal.
@jeremiehelme please look at the screens and remember this issue as a reference for possible new issues / screens!
