### ISSUE TITLE
GEO filter returns no data

### ISSUE THREAD

**Issue by SamuelPetragallo** [WorldHealthOrganization/herams-backend#108]
Applied a filter on GEO (the whole of Borno State) / NGA / Prod --> no points returned

**Comment by SamMousa** [comment]
Probably due to question code changes, has this worked since those changes?

**Comment by SamuelPetragallo** [comment]
I don't think I've looked at it since indeed

I need to have NGA data fixed (and use standard GEO1 question) - will look at that tomorrow and update you

**Comment by SamMousa** [comment]
By the way, we could use the select 2 component to implement those filters; it will make the implementation significantly simpler: https://select2.org/getting-started/basic-usage#multi-select-boxes-pillbox

**Comment by SamuelPetragallo** [comment]
Would that be the equivalent of what you have implemented in the ls form for GEO1 (i.e. search/select tool)?

**Comment by SamMousa** [comment]
Yeah

**Comment by SamuelPetragallo** [comment]
Great!

**Comment by SamMousa** [comment]
This is now functional on staging, but we need to redesign the filters to make it look right.
We could use select2 for all checkbox filters (like the advanced filters) as well; to make it consistent for the end user.

What do you think?

**Comment by SamuelPetragallo** [comment]
Agreed Sam - (FYI will try to loop/train Fatma in so she can take over some of the testing as suggested)
