### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by be-novelt** [WorldHealthOrganization/herams-backend#109]
@SamMousa 
> here are icons of 
1. User profile
2. Admin
which are on the top right of the screens
The logout appears (text) when you click on the arrow on the right of the User profile icon.
[Profile+admin.zip](https://github.com/WorldHealthOrganization/herams-backend/files/3069719/Profile%2Badmin.zip)

**Comment by SamMousa** [comment]
The admin icon was already implemented.
It doesn't make much sense to have a drop down for just 1 option, instead we can just have a logout icon that is always visible.

The user profile is actually a user chosen image, I will check if we can have gravatar default to the provided image.

**Comment by SamMousa** [comment]
Also, the user profile image doesn't use the current color so I can't change its color via CSS like I can with other SVG images.

Can you instead of making it white just use the current stroke as you did with the other images?

**Comment by SamMousa** [comment]
Icons are missing for the following:
- Stop / pause / deactivate something (this is 1 icon).
- Start / unpause / activate something (1 icon).
- Edit data (currently we have 1 edit icon which we use for editing properties, need a different one for data submission):
![image](https://user-images.githubusercontent.com/547021/56130580-9b29ae80-5f85-11e9-9b14-ce88536e014c.png)


- Share
