### ISSUE TITLE
Dash Map / MOZ / order answer options in the legend

### ISSUE THREAD

**Issue by SamuelPetragallo** [WorldHealthOrganization/herams-backend#110]
The legend of the map places Health Posts in the second position

Most likely due to the fact that Health Post answer code= A11 (hence placed in between A1 and A2)

**Comment by SamuelPetragallo** [comment]
NB: A1 (Teaching Hospital) was a mistake - I removed it - now Health Post (A11) comes first

**Comment by SamMousa** [comment]
I'm not sure what the issue is. The legend is ordered alphabetically as specified, so just make sure the answer codes are correct and it will work.
