### ISSUE TITLE
Permission removal

### ISSUE THREAD

**Issue by SamMousa** [WorldHealthOrganization/herams-backend#118]
Support permission removal for implicit admins.

**Comment by SamMousa** [comment]
This should allow deleting a workspace share when you have at least WRITE permission on the project.

**Comment by SamuelPetragallo** [comment]
Does this mean that with write permission a user can manage other users on the WS (in addition to managing the data)?

**Comment by SamMousa** [comment]
WRITE on the Project means you can manage workspaces for that project, yes.
