### ISSUE TITLE
Sudan / User can't access WS

### ISSUE THREAD

**Issue by SamuelPetragallo** [WorldHealthOrganization/herams-backend#119]
User 10433 can't access WS 509 although access has been granted both at Project and WS level (verified by me impersonating the user)

**Comment by SamMousa** [comment]
Currently admin permissions on the WS is needed to update limesurvey data.

**Comment by SamuelPetragallo** [comment]
Is that temp? I thought we had split both admin and data access but may have gotten that wrong.
Also share option text is confusing in this case: 
1. Manage the underlying response data or 
2. Full access, includes editing the workspace properties, token and response data

**Comment by SamMousa** [comment]
Could be that I got it wrong; but since the workspace itself only has a name it makes sense to have it at the same level.

**Comment by SamMousa** [comment]
This should be fixed; please test and confirm.

**Comment by SamuelPetragallo** [comment]
Good to go
