### ISSUE TITLE
Users with previous access to WSs - not automatically granted access to Project level and hence can't access WSs

### ISSUE THREAD

**Issue by SamuelPetragallo** [WorldHealthOrganization/herams-backend#120]
That seems to apply to all projects that already had WS users before new permission system rolled out

**Comment by SamMousa** [comment]
Everyone should see the full list of projects and for each project the workspaces list button should be available.

**Comment by SamuelPetragallo** [comment]
The access from the popups no longer seem to show, which is the main entry point for most users

**Comment by SamMousa** [comment]
Not sure what screen you mean here.

**Comment by SamuelPetragallo** [comment]
I meant the "Details" entry point on the project popup on the worldmap

**Comment by SamMousa** [comment]
Do the people have read permission? Read is needed to go to the project dashboard.
