### ISSUE TITLE
Sudan project - discrepancy between the map, chart, and actual data in LS

### ISSUE THREAD

**Issue by FatmaGiha** [WorldHealthOrganization/herams-backend#122]
In Sudan project dashboards, I am not sure if the Condition and Functionality pages read from the correct source. There are discrepancies between presented info on charts and map vs., the dataset on limesurvey
I exported data and ran the analysis manually and the produced results don’t match the dashboard results, as follows:
Functionality Page:
Data in LS: 
Fully Functioning: A1 = 39 responses 
NF: A3 = 1 response

Map: 
Fully Functioning = 27 responses
Unknown: 895 responses

Chart:
Fully Functioning: A1 = 37 responses
Partially Functioning = 1 response

Please advise of this issue

**Comment by SamMousa** [comment]
Have you checked that:
- Each token is connected to a workspace
- Each of the responses has GPS data (otherwise it cannot be shown on the map)

I'm not sure anything is wrong to be honest.

**Comment by SamuelPetragallo** [comment]
@FatmaGiha I have compiled the variables that are required for any given response stored in .ls to be considered in the dasboards analysis here: https://github.com/WorldHealthOrganization/herams-backend/wiki/MoSD-HF-Minimum-Variables . Could you please have a look and verify whether this explains the discrepancies you found?

**Comment by SamMousa** [comment]
As discussed in Skype, this is a data issue not a platform issue.
