### ISSUE TITLE
Open access to Project dashboards

### ISSUE THREAD

**Issue by SamuelPetragallo** [WorldHealthOrganization/herams-backend#123]
Up to now project dashboards were opened. We discussed the possibility of implementing a access permission granting mechanism to allow country focal point (project admins) manage access to their respective project dashboards. However we are currently "stuck half-way": project dashboards are no longer opened to all registered users, but registered users can't request access. Additionally we need to maintain the possibility of keeping a project opened to all registered users (as we are pushing for max dissemination of HeRAMS data).

Suggestion for now (until the full request/permission granting loop is in place) is to leave all projects opened up

**Comment by SamuelPetragallo** [comment]
Next release would be great if not too heavy as currently demoing to senior management

**Comment by SamuelPetragallo** [comment]
Access button ("Details") now seems to be visible to all users, but access still not granted 
![image](https://user-images.githubusercontent.com/15345099/57528940-e7250480-7333-11e9-8a32-94c4ab1b111e.png)

**Comment by SamMousa** [comment]
Hmm, try now.

**Comment by SamuelPetragallo** [comment]
Access to dashboards ok now - but dashboards all empty including for admin - ?
![image](https://user-images.githubusercontent.com/15345099/57530710-18073880-7338-11e9-9a8d-24062a4db480.png)

**Comment by SamuelPetragallo** [comment]
Got slightly more but still no actual data
![image](https://user-images.githubusercontent.com/15345099/57531128-10945f00-7339-11e9-932d-a57842e7c0a8.png)

**Comment by SamMousa** [comment]
That's was a separate issue with the location filter (which has now been fixed.

**Comment by FatmaGiha** [comment]
I checked this with random users, and the “Details” button is not always available to all registered users. Also, access to dashboards is not granted to many of the tested registered users; when I click on “Details”, an error message bounces back “Operation not allowed”

**Comment by SamMousa** [comment]
On staging?

**Comment by FatmaGiha** [comment]
Oops sorry, I was on the Production env., still learning on these... I have now tested the staging env. with random users and access to dashboards is working, except for Philippine and Pakistan (which I guess is normal here)

**Comment by SamMousa** [comment]
> except for Philippine and Pakistan (which I guess is normal here)

These kinds of sentences create confusion. Try to leave as little room for interpretation as possible. PHL and PAK have no dashboard configured so the button is not shown.
