### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by SamuelPetragallo** [WorldHealthOrganization/herams-backend#124]
Project status still offers various options - but selecting any other option than "ongoing" leads to rendering of an empty map.

Suggestion is to clear options and only keep "Ongoing" and "In progress".

"In progress" would translate into the project being located on worldmap and an "In progress" mention in the project popup. That would allow us map out project that we are working on setting up but for which there is currently no data accessible

**Comment by SamuelPetragallo** [comment]
Next release would be great if not too heavy as currently demoing to senior management

**Comment by SamMousa** [comment]
This has been fixed, no changes have been made to the status options for a project.

**Comment by SamuelPetragallo** [comment]
Rendering of worldmap now works

(Project status options remain unchanged (I think that's what you're saying - just making sure) - shall I create a new issue for that?)

**Comment by SamMousa** [comment]
if you want it changes yes; but that seems like low priority to me.

**Comment by SamuelPetragallo** [comment]
The useful thing here would have been to be able to flag projects that are "In progress" and avoid users misunderstanding/frustration when opening up pop-ups - depending on workload required (that popup would be empty apart from the "In progress" message)
