### ISSUE TITLE
How to map Service Availability

### ISSUE THREAD

**Issue by SamuelPetragallo** [WorldHealthOrganization/herams-backend#128]
Could you please describe the map configuration required to display service availability (knowing that we'll need various levels of aggregation: Overview (all), then per Sub-sector (question groups) then per Service (question)

**Comment by SamuelPetragallo** [comment]
NB: the config used for the Service Availability chart (below) doesn't work for the map

{
    "map": {
        "A1": "Fully available",
        "A2": "Partially available",
        "A3": "Not available",
        "A4": "Not normally provided"
    },
    "code": "availability",
    "colors": [
        "green",
        "orange",
        "red",
        "grey"
    ]
}

**Comment by SamMousa** [comment]
Support for this has not yet been implemented.
