### ISSUE TITLE
Support the map display of Service Availability

### ISSUE THREAD

**Issue by SamuelPetragallo** [WorldHealthOrganization/herams-backend#129]
Level of aggregation to be considered: from overview (all) down to individual services (i.e. questions) with service groups (question groups) in between

**Comment by SamMousa** [comment]
Isn't this the same as what we currently have for Nigeria?

Could be that the only thing we need to add is the option to add these automatically generated page(s) for every group.

**Comment by SamuelPetragallo** [comment]
They are not the same as in the groups (and number of) and questions within those may change - but other than that they are indeed structurally the same (and the dashboards to be displayed too). Would be great to have that automated!

**Comment by SamuelPetragallo** [comment]
(Note that we may want to display services within a group in the form of tabs vs adding one more level to the left menu - as suggested by Bruno)
