### ISSUE TITLE
Map/Chart customization - allow definition of color per response label

### ISSUE THREAD

**Issue by SamuelPetragallo** [WorldHealthOrganization/herams-backend#130]
Currently unclear how colors are attributed (including for automatic values such as "Unknown") - no big deal but would definitely benefit from a user interface displaying the answer labels (and automated values) and allowing color picking for each

**Comment by SamMousa** [comment]
Maybe better to do this from a requirements perspective instead of how it currently works. What is needed exactly?

**Comment by SamuelPetragallo** [comment]
The ideal would be a clear list of the all potential variables (answer code and answer label + "additionnal variables" ("unknown" etc.)) aside which users can assign  color

**Comment by SamMousa** [comment]
So it is a hard requirement to have fully customizable colors for each chart?

**Comment by SamuelPetragallo** [comment]
I think the original requirement sill holds - but the behavior of the current system is somewhat unpredictable (in parts due to the automatic addition of "unknown etc. and the unpredictable order of responses)

**Comment by SamuelPetragallo** [comment]
Well actually - we may also have the case where "Not applicable" is one of the response options: using a red/green scale in this case would result in having N/A portrayed red or green, which we don't want. So maybe it is a hard requirement to have fully customizable colors for maps and charts (depending on complexity as always)
