### ISSUE TITLE
Project summary/popup - hide graphs with no data

### ISSUE THREAD

**Issue by SamuelPetragallo** [WorldHealthOrganization/herams-backend#131]
Condition graphs display to availability of data.
Currently, "empty icons" of functionality and service availability are displayed regardless

![image](https://user-images.githubusercontent.com/15345099/57858252-fc48da00-77f0-11e9-95d3-20b5f6cd3878.png)

**Comment by SamMousa** [comment]
The charts are gone, but the popup is not yet resized.

**Comment by SamuelPetragallo** [comment]
What do you mean by "the popup is not yet resized" (initial thinking is the popup can/should keep the same dimension regardless)
