### ISSUE TITLE
Manual data sync

### ISSUE THREAD

**Issue by SamMousa** [WorldHealthOrganization/herams-backend#132]
At a workspace level data can now be manually synchronized.
![image](https://user-images.githubusercontent.com/547021/57923670-370b4a80-78a3-11e9-81cb-9982961feacc.png)

![image](https://user-images.githubusercontent.com/547021/57923687-412d4900-78a3-11e9-82f2-1d122595071e.png)

You must be workspace admin to access this feature.

**Comment by SamuelPetragallo** [comment]
That's a beauty - can we rename the function "Sync data to dashboards" (better without mention of ls)
