### ISSUE TITLE
#HFs on www.herams.org seems random (and randomly changes)

### ISSUE THREAD

**Issue by SamuelPetragallo** [WorldHealthOrganization/herams-backend#137]
![image](https://user-images.githubusercontent.com/15345099/58559161-c3622980-8222-11e9-9ee3-8a6f97eb748d.png)

**Comment by SamuelPetragallo** [comment]
![image](https://user-images.githubusercontent.com/15345099/58559176-cbba6480-8222-11e9-8e02-108a771b76b7.png)

**Comment by SamuelPetragallo** [comment]
Latest update also coming out funny :D

![image](https://user-images.githubusercontent.com/15345099/58559533-9d895480-8223-11e9-8807-a347d63a08f0.png)

**Comment by SamMousa** [comment]
https://ls.herams.org/admin/responses?sa=view&surveyid=418614&id=16797
The data is wrong.

Changing numbers was a feature, meaning you could observe herams going over all data. 
I've disabled that now.

**Comment by SamuelPetragallo** [comment]
Wrond date has been edited - and totla numbre displayed only now - great, thanks!
