### ISSUE TITLE
Footer display

### ISSUE THREAD

**Issue by SamuelPetragallo** [WorldHealthOrganization/herams-backend#139]
![image](https://user-images.githubusercontent.com/15345099/58695217-1825b180-8395-11e9-85e1-cceef57ab9c6.png)

**Comment by SamMousa** [comment]
Try refreshing / clearing browser cache.

**Comment by SamMousa** [comment]
Can you confirm this is still an issue?

**Comment by SamuelPetragallo** [comment]
No longer an issues indeed, thanks!
