### ISSUE TITLE
Leaflet Map / Implement a maximum zoom

### ISSUE THREAD

**Issue by SamuelPetragallo** [WorldHealthOrganization/herams-backend#140]
In some cases (like when there's 1 HF only) map zooms in so close that it has no background to display

![image](https://user-images.githubusercontent.com/15345099/58710201-10c5ce80-83bc-11e9-8880-1d2feeb448de.png)

**Comment by SamuelPetragallo** [comment]
Seems now that the background is "frozen" and no longer disappears - but the image then degrades. Ideally the zoom level should be caped. Think that when we have a (roughly) 1km2 window it's good enough - i.e. when the bar shows "100m" as in the screenshot below:

![image](https://user-images.githubusercontent.com/15345099/59264406-551a5f80-8c43-11e9-8ccc-80be1992ff52.png)

**Comment by SamMousa** [comment]
Now the max zoom is limited to 1 + most detailed tile available.

**Comment by SamuelPetragallo** [comment]
Great!
