### ISSUE TITLE
My ls admin account

### ISSUE THREAD

**Issue by SamuelPetragallo** [WorldHealthOrganization/herams-backend#142]
Have had issues accessing direclty to ls.herams lately with my admin account - and realized my herams/SSO account doesn't have full ls admin. Would it be possible to grant my SSO full admin so I don't even need to bother about the other one anymore?

Thanks!

**Comment by SamMousa** [comment]
Not sure; I have the same access as you do...
You can try to reset the admin password.

**Comment by SamuelPetragallo** [comment]
I've tried but didn't receive anything (tried with **admin** / **petragallos@who.int** think those are my admin credentials)

**Comment by SamMousa** [comment]
They are *-)

**Comment by SamuelPetragallo** [comment]
Can you check if emails have been sent (I've tried a few times ;) )

**Comment by SamuelPetragallo** [comment]
It seems my herams account now has full admin  rights -correct?

**Comment by SamMousa** [comment]
Yeah, I changed it!
Also reset the password still on my todo to send it to you? (Or  is that no longer needed since you are now super admin)

**Comment by SamuelPetragallo** [comment]
I was probably the only one to access directly - so should no longer be an issue

**Comment by SamuelPetragallo** [comment]
Solved as far as I'm concerned - up to you how you want to tag/close
