### ISSUE TITLE
Staging / Access to dahsboard edit dysfunctions

### ISSUE THREAD

**Issue by SamuelPetragallo** [WorldHealthOrganization/herams-backend#144]
User 10155 granted full access to Yemen and Nigeria on staging - but can't edit graphs/charts 

![image](https://user-images.githubusercontent.com/15345099/58791960-823b9200-85f3-11e9-9668-3561864a0e70.png)

**Comment by SamMousa** [comment]
Creation / updating is fixed, delete still todo.

**Comment by SamMousa** [comment]
Everything is ready for testing
