### ISSUE TITLE
Staging - new user can't register

### ISSUE THREAD

**Issue by SamuelPetragallo** [WorldHealthOrganization/herams-backend#145]
Trying to have a colleague register to staging to start training/supporting country roll-out in Zimbabwe - but registration returned the following error

![staging error](https://user-images.githubusercontent.com/15345099/58812353-fa20b100-8621-11e9-8dbf-a8265c606335.png)

**Comment by SamMousa** [comment]
Try now.

**Comment by SamuelPetragallo** [comment]
Swift_TransportException
Connection could not be established with host [php_network_getaddresses: getaddrinfo failed: Name or service not known #0]
1. in /home/www/sites/herams-staging.org/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php at line 269
260261262263264265266267268269270271272273274275276277278            $options['socket']['bindto'] = $this->params['sourceIp'].':0';
        }
 
        if (isset($this->params['stream_context_options'])) {
            $options = array_merge($options, $this->params['stream_context_options']);
        }
        $streamContext = stream_context_create($options);
        $this->stream = @stream_socket_client($host.':'.$this->params['port'], $errno, $errstr, $timeout, STREAM_CLIENT_CONNECT, $streamContext);
        if (false === $this->stream) {
            throw new Swift_TransportException(
                'Connection could not be established with host '.$this->params['host'].
                ' ['.$errstr.' #'.$errno.']'
                );
        }
        if (!empty($this->params['blocking'])) {
            stream_set_blocking($this->stream, 1);
        } else {
            stream_set_blocking($this->stream,

**Comment by SamuelPetragallo** [comment]
![image](https://user-images.githubusercontent.com/15345099/58864905-da3acd00-86b5-11e9-862a-add0d7a2ec69.png)

**Comment by SamMousa** [comment]
Try now, password reset works so mailing works, so I think sign up will work!
