### ISSUE TITLE
Change "platform's email address"

### ISSUE THREAD

**Issue by SamuelPetragallo** [WorldHealthOrganization/herams-backend#146]
For the lack of a better word: when registering, I got the confirmation from **prime_support**@herams-staging.org - guess it would be prime_support@herams.org - could be support@herams.org (but we then also need to set that up)

**Comment by SamMousa** [comment]
Nope, for staging it will end in staging; this is configuration that is environment specific.

**Comment by SamuelPetragallo** [comment]
On prod (just tested now) it is prime_support@who.int - can we make that herams@who.int instead please?

**Comment by SamuelPetragallo** [comment]
Yes you're right - support@herams.org is perfect thanks!

**Comment by SamMousa** [comment]
Done; after testing feel free to close this!
