### ISSUE TITLE
Registration message is wrong

### ISSUE THREAD

**Issue by SamuelPetragallo** [WorldHealthOrganization/herams-backend#147]
You have successfully registered to HeRAMS, the Public Health Risk Information Marketplace.To activate your account please follow this link:https://herams-staging.org/user/confirm/10392/QouAY8rN4_MCiOeYtROlHjlDo-0ZSaFxIf you cannot click the link, please try pasting the text into your browser.The Prime Team. | You have successfully registered to HeRAMS, the Public Health Risk Information Marketplace.To activate your account please follow this link:https://herams-staging.org/user/confirm/10392/QouAY8rN4_MCiOeYtROlHjlDo-0ZSaFxIf you cannot click the link, please try pasting the text into your browser.The Prime Team.
-- | --
You have successfully registered to HeRAMS, the Public Health Risk Information Marketplace.To activate your account please follow this link:https://herams-staging.org/user/confirm/10392/QouAY8rN4_MCiOeYtROlHjlDo-0ZSaFxIf you cannot click the link, please try pasting the text into your browser.The Prime Team.

**Comment by SamuelPetragallo** [comment]
Use the following please:
1. message title: Welcome to HeRAMS, the Health Resources and Services Availability Monitoring System
2. body: You have successfully registered to HeRAMS, the Health Resources and Services Availability Monitoring System.

To activate your account please follow this link:

https://herams.org/user/confirm/417891funwiwèofji

If you cannot click the link, please try pasting the text into your browser

3. insert (in small) the attached logo as a "signature" to that message

[HeRAMS_Horizontal_withoutbaseline.pdf](https://github.com/WorldHealthOrganization/herams-backend/files/3260838/HeRAMS_Horizontal_withoutbaseline.pdf)

**Comment by SamuelPetragallo** [comment]
Body message ok / Email title still needs to be changed

**Comment by SamMousa** [comment]
Should be fixed.
