### ISSUE TITLE
Prod / ls expands out of the iframe when opening a survey

### ISSUE THREAD

**Issue by SamuelPetragallo** [WorldHealthOrganization/herams-backend#150]
ls first opens up in a frame as planed, but then expands out (for example when opening up a survey) with no more access to herams other than browser back button

**Comment by SamMousa** [comment]
This is a bug in LS, lots of navigation uses a method that escapes iframes.
We can fix this but will have to fork the LS that is maintained by Denis.
I don't see much downsides to this since at this point the LS version we use is no longer being developed so there are few changes...

**Comment by SamuelPetragallo** [comment]
Would that be solved by an upgrade to latest stable ls?

**Comment by SamMousa** [comment]
Not for all instances, but some if them might be implemented differently...
Note that LS3 supports better admin theming, so we could fix it in the theme.

**Comment by SamuelPetragallo** [comment]
Let's look at that closely when you come - feel it would be good if we're able to make that move so at least we know, generally speaking, we are not hampered by the fact that we are running of a old version
