### ISSUE TITLE
Metrics on the login page - not overwritten by project level metrics?

### ISSUE THREAD

**Issue by SamuelPetragallo** [WorldHealthOrganization/herams-backend#152]
The 28k HFs that we are about to upload for PHL are mentioned in the project config and overwrite the metric in the project summary popup - but don't seem to affect the login page metric

**Comment by SamMousa** [comment]
Did you wait till the cache is refreshed? (Just to rule out a cache issue)

**Comment by SamuelPetragallo** [comment]
Yes. Note the 28k have not yet been uploaded - but they are mentioned in the project config. Seems the project summary popup picks on the config metrics whereas the overall metrics don't (only pick from HFs uploaded in ls)

**Comment by SamMousa** [comment]
I don't think this is still applicable.
