### ISSUE TITLE
Get NGO status

### ISSUE THREAD

**Issue by SamMousa** [WorldHealthOrganization/herams-backend#154]
Information needed:

- [x] Your nonprofit’s GitHub organization account name
- [x] Your nonprofit’s GitHub organization URL
- [ ] Proof of nonprofit status with your local government (501(c)(3) status in the US)
- [ ] The registered name of your nonprofit
- [ ] A summary of what your nonprofit organization does
- [ ] Confirmation that your organization is nongovernment, nonacademic, noncommercial, nonpolitical and has no religious affiliation

**Comment by SamuelPetragallo** [comment]
Sam can you tell me where I need to go for the request?

**Comment by SamMousa** [comment]
https://github.com/nonprofit
