### ISSUE TITLE
Outpatient services of 9 tertiary hospitals in NGA (filtered by type of HF; 9 tertiary hospitals)

### ISSUE THREAD

**Issue by JeffDotingco** [WorldHealthOrganization/herams-backend#156]
HeRAMS staging for outpatient services:
1. Filtered the dashboard into tertiary hospitals only
2. Upon checking, there are 9 tertiary hospitals
3. But in staging, the number with fully available outpatient services is n=513 or 100% fully available outpatient services filtered by type of HF (tertiary hospital)
4. 9 hospitals should appear as the total and not 513
<img width="1680" alt="Screen Shot 2019-07-08 at 10 39 55 PM" src="https://user-images.githubusercontent.com/50957748/60819422-222ba300-a1d2-11e9-9026-5657baac09d9.png">

**Comment by SamMousa** [comment]
This is because for those charts the `Transpose` options is enabled.
Transposing means that each row in the data set is converted to  a separate row per service.
Try disabling that in those charts.

**Comment by JeffDotingco** [comment]
Thanks! working now! 9 tertiary hospitals in total.

**Comment by JeffDotingco** [comment]
Another query: the total number for outpatient services should correspond to the total number of HFs excluding those that are fully damaged, non-functioning and not accessible. This is based on the conditions created for the questionnaire --automatically stops if HFs are either fully damaged or non-functioning or not accessible.

<img width="1680" alt="Screen Shot 2019-07-08 at 11 28 09 PM" src="https://user-images.githubusercontent.com/50957748/60822805-ba2c8b00-a1d8-11e9-853b-f5b16b4d5f71.png">

**Comment by JeffDotingco** [comment]
<img width="1680" alt="Screen Shot 2019-07-08 at 11 34 32 PM" src="https://user-images.githubusercontent.com/50957748/60822948-04ae0780-a1d9-11e9-87eb-a4f9e4f44fe8.png">

**Comment by SamMousa** [comment]
@JeffDotingco I'm closing this issue since it was resolved.

If you have another question please create a new issue and try to be a bit more clear.
