### ISSUE TITLE
Total number for outpatient services should correspond to the total number of HFs excluding those that are fully damaged, non-functioning and not accessible

### ISSUE THREAD

**Issue by JeffDotingco** [WorldHealthOrganization/herams-backend#157]
The total number for outpatient services should correspond to the total number of HFs excluding those that are fully damaged, non-functioning and not accessible. This is based on the conditions created for the questionnaire --automatically stops if HFs are either fully damaged or non-functioning or not accessible.

<img width="1680" alt="Screen Shot 2019-07-08 at 11 34 32 PM" src="https://user-images.githubusercontent.com/50957748/60824267-e09ff580-a1db-11e9-82a1-d17ee1a6f2a8.png">

**Comment by SamMousa** [comment]
This is not a question, but a statement.

Is the data that you see in the dashboard different from the data?

**Comment by JeffDotingco** [comment]
Hi Sam, is there an automatic code so that the total HFs should correspond to total number of HFs excluding those that are fully damaged, non-functioning and not accessible when it comes to the health services part? Because we have conditioned this part of the questionnaire so that it will automatically stop once the response is fully damaged or non-functioning or not accessible.

**Comment by SamMousa** [comment]
No, the platform doesn't use any logic like that. Limesurvey should clear irrelevant data from the response.

**Comment by JeffDotingco** [comment]
Okay Sam. Thanks for the clarification.

**Comment by JeffDotingco** [comment]
I made a remedy of making the figures close through filtering. So "fully damaged", "non-functioning", and "not accessible" was excluded in the filter. :) Some HFs might have incomplete responses of 5 missing data on the health services part. Good night! 
<img width="1680" alt="Screen Shot 2019-07-09 at 1 14 45 AM" src="https://user-images.githubusercontent.com/50957748/60829324-39c15680-a1e7-11e9-96f2-d1eec01a0854.png">

**Comment by SamMousa** [comment]
The filters are not saved so it doesn't matter.
