### ISSUE TITLE
Refine "unknown" values display

### ISSUE THREAD

**Issue by SamuelPetragallo** [WorldHealthOrganization/herams-backend#158]
Currently all empty fields (meaning empty fields as well as "question not showned" fields for example are lumped under "Unknown" in the charts/maps

In Moz, those are mostly unknown indeed, but in Nigeria for example they are mostly "question not showned", meaning for e.g. there is no "Service avail" answer because the facility is destroyed or not functional and hence the service question was "not shown" to the respondant

Need to discuss how to better represent that

**Comment by SamMousa** [comment]
A possible solution would be to add a default value to those questions and make them mandatory.
That way we get 2 categories.
This would need testing (do these default values get cleared, or do they remain in the data?)

What we should really not do is implement survey logic in the platform on the analysis side.

**Comment by SamMousa** [comment]
Add service default via LS equation question
