### ISSUE TITLE
Create help videos

### ISSUE THREAD

**Issue by SamMousa** [WorldHealthOrganization/herams-backend#159]
Instead of adding screenshots and spending (lots of) time on text explanations, we can use videos that show how users can do things.

The videos should be short and show specific parts of workflows.

**Comment by luna404** [comment]
This goes a little bit beyond just the help videos, but I thought I still post it in here. 

As not everyone is equally familiar with GitHub, I thought I create a brief demo version to illustrate how a user manual might look like. 

[GitHub user manual demo ](https://github.com/luna404/HeRAMS-UserManual/blob/master/UserGuide_en.md)

- If you click on the link français just below the title, you will see that it opens the french version of the user manual. 
- While it would still require to maintain different versions for different languages, we could make sure that  any image/image is automatically updated in all versions.  
- Short videos (similar to the ones embedded in the doc) could be nice feature to improve user experience. 

I would also like to start a general discussion on the purpose / audience of the user guide and how it is best structured. Personally, I would favor a structure that focuses on tasks a user needs to accomplish or to help troubleshoot issues encountered. The user manual developed by Jeff for the [Philippines](https://drive.google.com/open?id=1QTXcnjKwBUnGVYKgRHvqcfPJMCsnlm9T) is a good example of this structure. I tried to follow a similar approach in the [french ](https://drive.google.com/open?id=1AdcsZM0dL7zZjLmjSHhgl3bbgU36s66d) version, but there is still a lot of room for improvement 😇. 

What do you guys think?

**Comment by SamMousa** [comment]
Cool!
I'm not a fan of using gifs for the movies though; makes it harder to pause
/ step through them.

**Comment by luna404** [comment]
Agreed, but I could only make it work using gifs. Do you have an idea of alternative format?
I can create the videos either in mp4 or gifs and Github seems to not be supporting the mp4. At least it didn't work for me when I tried it this morning.

**Comment by SamMousa** [comment]
Depends on where you put it, Github Pages and the Wiki should support it. (You can set up Pages from a repo)
