### ISSUE TITLE
No HF GPS coordinates shown in the dashboard map for HeRAMS Cox's Bazar.

### ISSUE THREAD

**Issue by JeffDotingco** [WorldHealthOrganization/herams-backend#164]
Need some help also on this. No HF GPS coordinates are appearing in the dashboard map for HeRAMS Cox's Bazar. I don't know if there is a configuration needed for the "dots" to appear in the map. Thanks

**Comment by SamMousa** [comment]
... as far as I can tell, from looking at the data in LS, there are no GPS coordinates in the data; they are all empty.
@JeffDotingco you are wasting a lot of my time; from now on tell me what you have checked to resolve the *issue*; that way I know not to spend time if you have not done any basic research yourself.

**Comment by JeffDotingco** [comment]
Okay. I'll check again the importing of the dataset.

**Comment by JeffDotingco** [comment]
Hi @SamMousa good morning! Sorry for raising invalid issues. After you have discovered that there are no coordinates in the data, I figured there is something wrong with the import and after that I sorted the issue out. I will not raise an issue again to you unless it is something I myself cannot resolve in the future.
