### ISSUE TITLE
GPS coordinates don't display in data update form

### ISSUE THREAD

**Issue by luna404** [WorldHealthOrganization/herams-backend#165]
**Survey id: 954572 (Tchad)
Fields: MoSDGPS_SQ001 ,MoSDGPS_SQ002**

GPS coordinates of health facilities are not loading in the data update view in HeRAMS. Data appears to be imported correctly as values are displayed in the data table (see below)

![data_table](https://user-images.githubusercontent.com/18245059/61548049-01264600-aa4d-11e9-914f-e8e1cda75603.PNG)

If a user edits the record, no values are displayed for fields MoSDGPS_SQ001 ,MoSDGPS_SQ002
![GPS_error](https://user-images.githubusercontent.com/18245059/61548089-18653380-aa4d-11e9-908d-6271bca672fc.PNG)

**Comment by SamMousa** [comment]
The GPS question had a relevance equation / condition based on a question on the page after.
Thus LS decided that at that point the GPS question is not relevant and data gets cleared.

I have removed the condition and now the GPS question is always visible and shows the value.

**Comment by luna404** [comment]
Thanks, I confirm it's working now. Should maybe have check this myself first...
