### ISSUE TITLE
Option to download data at project level

### ISSUE THREAD

**Issue by luna404** [WorldHealthOrganization/herams-backend#167]
Currently users are only able to export data at the workspace level. For administrators at the country level they sometimes have to see records for multiple or all workspaces. Would it be possible to add an export level at the project level to allow advanced users to export all data from HeRAMS without requiring access to LS.

Issue was raised during a TC with Chad

**Comment by FatmaGiha** [comment]
The same issue was reported in HeRAMS Sudan, and requests were raised by the country level administrators to add an export button on the users interface for the country-level dataset.

**Comment by JeffDotingco** [comment]
This was sorted out before in Yemen by providing MOH admins backend access in limesurvey by @SamuelPetragallo because they requested to have an access of downloading the whole dataset. This was also raised by DOH in PHL during the training.

**Comment by SamMousa** [comment]
@SamuelPetragallo you should decide on this.
Technically it's not an issue to implement this.

**Comment by SamMousa** [comment]
Implemented
