### ISSUE TITLE
API access for mapping purposes

### ISSUE THREAD

**Issue by luna404** [WorldHealthOrganization/herams-backend#168]
During informal discussion with the GIS team, access to the HeRAMS data was raised and whether we are planning on making subsets of the data available to import into "Esri land" so they can use it  as baseline data in event-specific maps. 
If a HeRAMS API were available, a feature service (esri term) could be created in ArcGIS online that permits the GIS team to access the data and would assure they always use the latest information available.

**Comment by JeffDotingco** [comment]
I think we have to think about this, from previous discussions HeRAMS ownership is with the respective MoH wherein they are sensitive of providing access to GPS locations of Health Facilities like the Department of Health of the Philippines, MoH of Yemen. I think Vanuatu MOH doesn't want to share the gps coordinates of HFs. It is up to them if they will allow access.
