### ISSUE TITLE
Remove old surveys

### ISSUE THREAD

**Issue by SamMousa** [WorldHealthOrganization/herams-backend#170]
Nigera has 3 surveys in LS, 2 of these should be removed.

**Comment by JeffDotingco** [comment]
Already addressed this to @SamuelPetragallo. In agreement of removing the old surveys but the following should be addressed first:
1. HeRAMS Nigeria (old) (ID 263555) should be removed but the user emails (KIs) per WS are embedded. 
2. HeRAMS Nigeria (GEO1 updated) (ID 567974) should be removed but the old question codes are being used in the dashboard.
3. HeRAMS Nigeria 2 (New SDM format) (ID 391149) has the updated question codes but it will affect the dashboard using the former codes not in line with the SDM.
