### ISSUE TITLE
Is there a way of identifying the actual observations used in the analysis of the dashboard from limesurvey?

### ISSUE THREAD

**Issue by JeffDotingco** [WorldHealthOrganization/herams-backend#172]
Is there a way of identifying the actual observations used in the analysis of the dashboard from limesurvey?

example: For HeRAMS NGA, there are 2746 health facilities analysed by the dashboard based on the latest responses made. But If I download the dataset from ls, there are 4841 complete responses stored (including duplicates based on UOID, but different "submit date" and "date of update"). 

I am anticipating this issue if the country office asks for some ad hoc analysis aside from the dashboard and I want to the analysis to reflect to the same number and record of health facility being analysed in the dashboard. 

I am thinking if the dashboard / platform could provide the "id" of health facilities analysed in the dashboard.

**Comment by SamuelPetragallo** [comment]
This is correct, but not sure we should go that far: we have listed the criteria used for HF import from ls to HeRAMS in the Wiki and the only other elements that may apply are filters used in HeRAMS. Those that will require/get and actually use the data download option from ls need to be few and savvy (that way we can manage that without developing adhoc features)
