### ISSUE TITLE
Staging dashboard - Map for Tchad not drwaing

### ISSUE THREAD

**Issue by luna404** [WorldHealthOrganization/herams-backend#174]
Dashboard: **Tchad** (project id = 18)
Maps in the dashboard don't display correctly.  The map doesn't show any points upon loading but works if filters are applied.
 
Without filter
![image](https://user-images.githubusercontent.com/18245059/62935276-fe5a0f00-bdc6-11e9-93e5-b79ed6cf27ad.png)

With filter applied on Geo1
![image](https://user-images.githubusercontent.com/18245059/62935251-e4b8c780-bdc6-11e9-82c9-a018f036e18e.png)

Dashboard on Prod
![image](https://user-images.githubusercontent.com/18245059/62935322-1c277400-bdc7-11e9-92c1-70e2cb40d45b.png)

**Comment by luna404** [comment]
The legend for **Service Availability** is not drawing. 

Example from Comoros below (https://herams-staging.org/project/27)
![Service_availability](https://user-images.githubusercontent.com/18245059/62935503-9952e900-bdc7-11e9-9ebb-40e1ba5afa3b.PNG)

**Comment by SamMousa** [comment]
@luna404 this is now fixed.
Out of bounds latitudes & longitudes are ignored on the map widget.
The response with ID 19355 was the culprit.
