### ISSUE TITLE
Staging dashboard - Service Availability Chart has wrong labels

### ISSUE THREAD

**Issue by luna404** [WorldHealthOrganization/herams-backend#175]
The legend for **Service Availability** is showing wrong labels. 

Example from Comoros below (https://herams-staging.org/project/27)
![Service_availability](https://user-images.githubusercontent.com/18245059/62935503-9952e900-bdc7-11e9-9ebb-40e1ba5afa3b.PNG)

**Comment by SamMousa** [comment]
Already fixed during the meeting ;-)
