### ISSUE TITLE
HeRAMS Nigeria: Causes of unavailability chart in Overview (sort position:5) and Service availability is not working

### ISSUE THREAD

**Issue by JeffDotingco** [WorldHealthOrganization/herams-backend#176]
1. Causes of unavailability chart in Overview (sort position:5) and Service availability in HeRAMS Nigeria is not working: I already changed the code to "the causes of unavailability" from GEO1 (default), seems to be working in the preview but not in the overview page.

<img width="1680" alt="Screen Shot 2019-08-14 at 6 33 41 PM" src="https://user-images.githubusercontent.com/50957748/63015149-ce903180-bec2-11e9-89e5-423e514842d5.png">

**Comment by SamMousa** [comment]
Fixed.

**Comment by JeffDotingco** [comment]
HI Sam, thanks, I can change the colors. Works fine in preview but not in the dashboard

<img width="1680" alt="Screen Shot 2019-08-14 at 10 13 36 PM" src="https://user-images.githubusercontent.com/50957748/63028230-01e1b900-bee1-11e9-9061-b266c880ae37.png">

**Comment by SamMousa** [comment]
I have found the cause of this issue, will work on a fix.

**Comment by JeffDotingco** [comment]
okay

**Comment by SamMousa** [comment]
I think this is fixed!

**Comment by JeffDotingco** [comment]
Yes, fixed now. But is there a way that we can decrease the legend fonts for the graph to appear?
