### ISSUE TITLE
Survey configuration / Limit update

### ISSUE THREAD

**Issue by SamuelPetragallo** [WorldHealthOrganization/herams-backend#177]
Would be useful to put a maximum date of the current date (included) for the Update field so we avoid mistakes and weird metrics on the welcome page which is where traffic will be highest

Exchange tips on how best to do that here if needed

**Comment by SamMousa** [comment]
Have implemented that here:
https://ls.herams.org/survey/index/action/previewquestion/sid/391149/gid/483/qid/7079

I think this can be rolled out to every survey.

**Comment by SamuelPetragallo** [comment]
@luna404 , Jeff, Fatma, can you implement that progressively in all your surveys, so update can never be  past the actual date? Thanks!
