### ISSUE TITLE
Dashboard import and export

### ISSUE THREAD

**Issue by SamMousa** [WorldHealthOrganization/herams-backend#178]
![image](https://user-images.githubusercontent.com/547021/63263869-fb10c880-c289-11e9-8eab-25f28c49a14c.png)

On the project update page you will find export and import buttons, give them a go, let me know what you think.

You can only export / import all pages at this time.

**Comment by JeffDotingco** [comment]
this is a great addition to the features of the dashboard where users can export pages that will surely be used by users

**Comment by luna404** [comment]
@SamMousa could you check the access permissions. I still get an "failed - forbidden" error when I try to export a dashboard.

**Comment by SamMousa** [comment]
Try now!
