### ISSUE TITLE
Water sources (HFMR1), energy source (HFMR4) and cold chain source (HFMR5) charts are not working for HeRAMS NGA Project (id:10)

### ISSUE THREAD

**Issue by JeffDotingco** [WorldHealthOrganization/herams-backend#184]
Water sources (HFMR1; id: 13), energy source (HFMR4; id: 15) and cold chain source (HFMR5; id: 16) charts are not working for HeRAMS NGA Project (id:10) under Basic Amenities. These charts used to work last week.
<img width="1680" alt="Screen Shot 2019-08-20 at 1 20 27 AM" src="https://user-images.githubusercontent.com/50957748/63286124-d77d6a80-c2e9-11e9-8fc4-60261f040d6c.png">

**Comment by SamMousa** [comment]
What have you already checked?

**Comment by JeffDotingco** [comment]
I checked the sorting of charts under Basic Amenities if okay, then I looked into the different charts separately to check.

<img width="1680" alt="Screen Shot 2019-08-20 at 1 25 47 AM" src="https://user-images.githubusercontent.com/50957748/63286516-cda83700-c2ea-11e9-9843-4ebc16c62d57.png">

**Comment by luna404** [comment]
I have the same problem with the Comoros dashboard. There are several charts that no longer draw, but used to last week. 
Indicators affect are [HFFUNTx](https://herams-staging.org/element/101/update), [HFBA1](https://herams-staging.org/element/103/update), `[HFBA3](https://herams-staging.org/element/107/update)`

**Comment by luna404** [comment]
I confirm this is working now. Thanks.
