### ISSUE TITLE
Multi language support for standard legend items

### ISSUE THREAD

**Issue by luna404** [WorldHealthOrganization/herams-backend#186]
This is not a bug but an enhancement request.

The labels for "Others" and "Unkown" are only available in English. It would be great if they could be adjusted based on the default language of the survey. 

![image](https://user-images.githubusercontent.com/18245059/63296924-8745de80-c2d0-11e9-8913-918a1ab62664.png)

The same applies to the "service availability" chart

![image](https://user-images.githubusercontent.com/18245059/63297042-c6742f80-c2d0-11e9-8bfe-168aa117f0e3.png)

**Comment by SamMousa** [comment]
We should translate all of the platform to different languages

**Comment by SamMousa** [comment]
- [ ] Make the application multi-lingual

**Comment by SamMousa** [comment]
@luna404 This is an example file that needs to contain translations: https://github.com/WorldHealthOrganization/herams-backend/blob/master/protected/messages/fr/app.php

I think you can click the link, then use the pencil to edit it. Afterwards GitHub will offer you the option to make a Pull Request.

When you have time (should take just 2 minutes) please go ahead and just translate 1 line and open the PR, this is to test the workflow.

**Comment by luna404** [comment]
I added a few translations and create the PR. Not sure how I would have to go about to add additional translations though

**Comment by SamMousa** [comment]
Superseded by #236
