### ISSUE TITLE
Not possible to reorder dashboard pages

### ISSUE THREAD

**Issue by luna404** [WorldHealthOrganization/herams-backend#187]
Unlike dashboard elements, it is not possible to change the order of dashboard pages after the page was created. 

When you create a new page, there is an option to add the **Sort ID.**
![image](https://user-images.githubusercontent.com/18245059/63333797-513d4480-c33a-11e9-9aa5-c5662f5eeb89.png)

This option is no longer available when you edit the page

![image](https://user-images.githubusercontent.com/18245059/63333896-86499700-c33a-11e9-94f5-b0d79b229cd8.png)

Would it be possible to keep the option to reorder the pages after the page was created?

**Comment by luna404** [comment]
Confirm it's working. One small thing, would it be possible to display the sort id in the table and sort them by id so they appear in order (same behavior has you have implemented for the dashboard elements.) Right now the order in the table doesn't correspond to the order in the dashbaord. 

![image](https://user-images.githubusercontent.com/18245059/63425456-dabf4600-c410-11e9-8349-f6975da33b6b.png)

![image](https://user-images.githubusercontent.com/18245059/63425476-e9a5f880-c410-11e9-957f-86f971949b6a.png)

**Comment by SamMousa** [comment]
The issue is that the pages are a tree not a list; I have added the sort column, but sorting needs to be done in a more complex way (since we still want to group child pages with their parent).
For now I'm going to leave it like this!
