### ISSUE TITLE
Create element colors overwritten

### ISSUE THREAD

**Issue by luna404** [WorldHealthOrganization/herams-backend#188]
As creating an element will overwrite the colors selected, it would be more user-friendly if the option to assign colors is only displayed after the element was created. 

At the moment, the option to assign colors appears as soon as the element is selected. However, if the element has not been created, the colors selected will be overwritten once the user clicks the “Create element” button. 

![Creating_elements_issue](https://user-images.githubusercontent.com/18245059/63336979-7765e300-c340-11e9-93c3-0fc12e270ed0.gif)

From a user experience perspective, this is not very intuitive and might frustrate users as they have to do the color assignment twice if they forget to first create the element.

**Comment by SamMousa** [comment]
Hmm, it should work on creation as well, this is a bug.

**Comment by luna404** [comment]
It's working for charts and maps, but when you create a table you also get to pick colors :)

![image](https://user-images.githubusercontent.com/18245059/63432628-c6d01000-c421-11e9-82d6-0dd34146a1e2.png)

**Comment by SamMousa** [comment]
Will fix that

**Comment by luna404** [comment]
There still seems to be an issue with the color overwriting in some case. I wasn't able to recreate it with any other variable but MoSD3, but it happened for both charts and maps. 

![color_overwritten](https://user-images.githubusercontent.com/18245059/63845243-fc2cae80-c989-11e9-9bee-4fb7bb764f97.gif)

**Comment by SamMousa** [comment]
I have changed the element creation workflow, it should be resolved now.

**Comment by luna404** [comment]
This is great. I have created a couple of new elements. Seems to working perfectly so far.

**Comment by luna404** [comment]
Sorry, I have to revert my previous comment. There is still an issue with the color overwriting. The issue seems to be related to the number of answer options. It's no problem if you create a chart with up to four options, but colors are still overwritten when there are more more answer options (e.g. MoSD3, HFBA2). I tested in two different projects (Comoros and Zimbabwe)

**Comment by SamMousa** [comment]
Hmm, try now!
