### ISSUE TITLE
Tooltips crop text

### ISSUE THREAD

**Issue by luna404** [WorldHealthOrganization/herams-backend#191]
Some of the tool-tips are too small to display the entire text string. Can we make them a little bigger or should abbreviate the text?

![image](https://user-images.githubusercontent.com/18245059/63432989-8e7d0180-c422-11e9-9787-8b72630e8b9c.png)

**Comment by SamMousa** [comment]
I'll see what I can do

**Comment by SamMousa** [comment]
The way tooltips are created does not allow us to draw outside the canvas.
One option would be to disable the tooltips for the summary (they don't add anything much anyway)

**Comment by SamMousa** [comment]
@SamuelPetragallo should I disable tooltips for the summary?

**Comment by SamuelPetragallo** [comment]
Yes agree to have them disabled
