### ISSUE TITLE
Element sizing

### ISSUE THREAD

**Issue by SamMousa** [WorldHealthOrganization/herams-backend#192]
Allow elements to have a user configurable size:
 - 1 x 1
 - 1 x 2
 - 2 x 1
 - 2 x 2

Possibly other sizes.

**Comment by SamMousa** [comment]
@luna404 you can now configure the size of elements, this should alleviate some of the legend issues.

**Comment by luna404** [comment]
Works great, but we should discuss some standard size for charts and maps.
