### ISSUE TITLE
Pop-ups on world maps don't work 

### ISSUE THREAD

**Issue by luna404** [WorldHealthOrganization/herams-backend#193]
The pop-ups on the world map don't work on staging. The error affects all projects.

![image](https://user-images.githubusercontent.com/18245059/63592786-c5821d00-c5b2-11e9-87bf-1cf17c4d1eb9.png)

**Comment by SamuelPetragallo** [comment]
I've realized that too. Can you guys still work efficiently on dashboards then? We may need to ping @SamMousa if urgent

**Comment by luna404** [comment]
Yes. It's still possible to open the dashboards from the admin interface, but you need access on the project level or if you know the project id you can just change the URL.

**Comment by SamuelPetragallo** [comment]
Guess it's not urgent then - @JeffDotingco are you ok working on dashboard still?

**Comment by JeffDotingco** [comment]
Hi @SamuelPetragallo, not anymore. The only opened issues for the dashboards are issue #179 (on changing the black color default of "others" in Health Facility Type (MoSD3) in HeRAMS NGA Project (id:10) and PHL Project (id: 23)) and Issue #180 ("Causes of Unavailability" graph in HeRAMS NGA is not shown).

**Comment by SamMousa** [comment]
I'll fix this Wednesday
