### ISSUE TITLE
Zimbabwe data not refreshing on staging

### ISSUE THREAD

**Issue by luna404** [WorldHealthOrganization/herams-backend#195]
I imported the data for Zimbabwe today. The data displays correctly on production

![image](https://user-images.githubusercontent.com/18245059/63786782-0354ad80-c8f3-11e9-8644-588bc8bc3ea0.png)

but not on staging.
![image](https://user-images.githubusercontent.com/18245059/63786718-ddc7a400-c8f2-11e9-867c-07b5e5eb9fbc.png)

However, if you click the date update button (on staging), the records are shown correctly. 

![image](https://user-images.githubusercontent.com/18245059/63787027-67777180-c8f3-11e9-9474-0d7744a096bf.png)

I tried to manually refresh the data, but it doesn't solve the issue. I also checked the data and there are no errors.

**Comment by SamMousa** [comment]
Could it be that the format of the date field is incorrect?
![image](https://user-images.githubusercontent.com/547021/63845788-dce25100-c98a-11e9-9293-fff64f79349b.png)

**Comment by luna404** [comment]
What's wrong with the date format? Isn't it supposed to be yyyy-mm-dd?
![image](https://user-images.githubusercontent.com/18245059/63846561-5dee1800-c98c-11e9-9508-283d46a0c24f.png)


The issue solved itself. The data is now displaying.

**Comment by SamMousa** [comment]
I thought it used to include a time as well; anyway great that it works!
