### ISSUE TITLE
Staging dashboard table  - group code displayed as integer

### ISSUE THREAD

**Issue by luna404** [WorldHealthOrganization/herams-backend#196]
If you create a new table in the dashboard on staging, the group by column displays values as integers instead of the label. See below example from Zimbabwe

https://herams-staging.org/element/283/update

![image](https://user-images.githubusercontent.com/18245059/63837139-2dea4900-c97b-11e9-8846-6bbddd067bcf.png)

**Comment by SamMousa** [comment]
This was caused by usage of numeric answer codes. The issue is now fixed.

**Comment by luna404** [comment]
Tested, issue is fixed.
