### ISSUE TITLE
Add header to dashboard maps or dashboard map legend

### ISSUE THREAD

**Issue by JeffDotingco** [WorldHealthOrganization/herams-backend#198]
Is it possible to add a title to the map on "aggregate availability of services per HF" in HeRAMS NGA staging in the overview page (id: 270, sort:6) and service availability overview page (id: 33, sort:0)?

<img width="1680" alt="Screen Shot 2019-08-28 at 11 13 07 PM" src="https://user-images.githubusercontent.com/50957748/63869520-d7b4ee80-c9ea-11e9-8098-d2c5005eff7e.png">

**Comment by SamMousa** [comment]
Can you try to generalize? Do you want a title for maps or for this specific map only.

**Comment by JeffDotingco** [comment]
just for the specific map. Or we can add a title to the legend of <25%, 25-50%, 50-75%, >75%

**Comment by luna404** [comment]
This might also be relevant to other questions. In the example below you only know what question is based on the title/context of the page. I think the option to add a title or legend header would also be beneficial in these cases. @SamMousa  would it be possible to have the ability to add an optional legend header?

![image](https://user-images.githubusercontent.com/18245059/63873850-a293a680-c9c0-11e9-841e-e810ccbf782f.png)

**Comment by SamMousa** [comment]
- Have added the question title to the maps
- Maps can now also map multiple choice / ranking questions; it uses the first selection to place a point on the map

**Comment by luna404** [comment]
Is working. Personally I would prefer to add it as a header to the legend rather than as a new text field. Also would it be possible to edit the label (alike the charts and tables)?

**Comment by SamMousa** [comment]
Will give it a go!

**Comment by SamMousa** [comment]
@luna404 try now!
