### ISSUE TITLE
Chart legend doesn't update if labels are changed in LS

### ISSUE THREAD

**Issue by luna404** [WorldHealthOrganization/herams-backend#199]
I corrected some labels in LS, but the changes are not reflected on the dashboard. I tried updating an existing chart and creating a new chart but the labels don't update. 

projects: Tchad & Comors, question CONDB

![image](https://user-images.githubusercontent.com/18245059/63924699-03ff5800-ca49-11e9-9dbe-6dd96af22a57.png)

![image](https://user-images.githubusercontent.com/18245059/63924751-1a0d1880-ca49-11e9-9d80-990c9b69bf3f.png)

Also it seems you truncate labels either based on length or after special character? Could you share the logic you used so we now what will/won't be displayed.

**Comment by SamMousa** [comment]
Separator is `:`. Structure is cached for several hours; so could take a while for it to become visible.

**Comment by luna404** [comment]
Ok, that's good to know. Could we add `(` as a separator too? 
@JeffDotingco and Fatma, what do you think?

**Comment by SamuelPetragallo** [comment]
> Ok, that's good to know. Could we add `(` as a separator too?
> @JeffDotingco and Fatma, what do you think?

Would that bring a lot of added value? First thought is this may create more unwanted behavior and ":" should suffice but may have missed something

**Comment by luna404** [comment]
It was just an idea to make label more concise. For example, for the reasons of unavailability, the brackets in the answer options makes the chart require width of 2. This could be avoided if the text in brackets could be removed. 

![image](https://user-images.githubusercontent.com/18245059/64183562-59cd6900-ce6a-11e9-8a16-bfb23c92dad6.png)

**Comment by SamuelPetragallo** [comment]
I see - guess inserting ":" instead of "(" for those would be painful at this stage

If so - may be an option indeed. I'm in favor of anything that can help us reduce these legends (it's indeed a pity to have to extend chart size just to accommodate for legends)

**Comment by SamuelPetragallo** [comment]
@SamMousa we run back into this issue with @luna404 earlier this evening when looking at the various options for dashboard layout. Adding "(" as a separator would most probably solve these issues and allow us NOT to adapt the dashboard layouts because of long legend labels.

So would really appreciate if "(" could be added to ":" as a separator - I hope it's not too much hassle.

Adding the appropriate tag accordingly in case ;), thanks! (If not possible @luna404 lets keep the layouts as if it was implemented not to have to redo them later)

**Comment by SamMousa** [comment]
It should be simple.

**Comment by SamuelPetragallo** [comment]
Great thanks @SamMousa ! @luna404 , @JeffDotingco we can keep the preferred layout and hope for a nice output!
