### ISSUE TITLE
Error deleting dashboard pages with elements

### ISSUE THREAD

**Issue by luna404** [WorldHealthOrganization/herams-backend#200]
It's not possible to delete a dashboard page that still contains elements. If you delete a page with elements you get the following error.
```
SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`herams2`.`prime2_element`, CONSTRAINT `element_page` FOREIGN KEY (`page_id`) REFERENCES `prime2_page` (`id`))
The SQL being executed was: DELETE FROM `prime2_page` WHERE `id`=46
```
Based on the above error message, I removed the elements first and then delete the page. This is working.

**Comment by SamMousa** [comment]
It still has elements.

**Comment by SamMousa** [comment]
Deletes should now cascade, so all child pages and elements will get deleted as well.

**Comment by luna404** [comment]
Tested for both child pages and pages with elements.
