### ISSUE TITLE
www.herams.org/TRAINING - ?

### ISSUE THREAD

**Issue by SamuelPetragallo** [WorldHealthOrganization/herams-backend#201]
Would be nice if we can already agree on how we will structure the additional pages on www.herams.org

Which sections - training, technical guidance, reports? - which structure?

Would be nice if we can nail that down as well as the respective URLs quite quickly so that we can already reference those in the e-learning (guess we still have 1 week of time for that - should hopefully be fine)

Thanks!

**Comment by luna404** [comment]
I would propose something like this 
https://herams.org/documentation
https://herams.org/documentation/training
https://herams.org/documentation/user-guide
....

For the user guide (and potentially also others) should we create individual pages for different languages? 
https://herams.org/documentation/user-guide-fr
https://herams.org/documentation/user-guide-en

**Comment by SamMousa** [comment]
I recommend letting the details like URLs up to a system that we use to manage publishing it.
(Often you see `/docs/LANG/user-guide`, no need to decide on something now)
URLs are not entered directly in most cases, they are used via links.

We should just identify the structure of the pages, not the URLs

**Comment by SamMousa** [comment]
@SamuelPetragallo I'm closing this since we now have https://docs.herams.org
