### ISSUE TITLE
Chart with CONDB misses 'Others'

### ISSUE THREAD

**Issue by luna404** [WorldHealthOrganization/herams-backend#202]
If you create a chart with the CONDB variable, others is not displayed. However, if you create a map with the same variable it is. 

See Zimbabwe - Building condition (https://herams-staging.org/project/26?page_id=74)

![image](https://user-images.githubusercontent.com/18245059/63934966-ca384c80-ca5c-11e9-93e8-0e7feaa4db04.png)

**Comment by SamMousa** [comment]
Sidenote: **Others** is not the same as **unknown**.

**Comment by SamMousa** [comment]
Reasoning for this behavior is as follows:
- The map will show geographical information, even if we don't know the value of whatever question is chosen for the legend.
- The map does not show a counter, so we need the number of dots to be equal to the number of HF in the top.
- The chart shows a total in the center, so here showing unknown doesn't provide extra information.

**Comment by luna404** [comment]
Thanks for the clarification. I disagree a little on the point that it doesn't provide additional information, but I see your point.

**Comment by luna404** [comment]
If charts never display 'Unkown', why don't we remove the option completely for charts to avoid confusion around this?

![image](https://user-images.githubusercontent.com/18245059/63939232-083a6e00-ca67-11e9-8b4e-7b9c5594345a.png)
