### ISSUE TITLE
All sub-pages are added to Nigeria dashboard

### ISSUE THREAD

**Issue by luna404** [WorldHealthOrganization/herams-backend#203]
If you create a sub-page in any project, they are added to Nigeria instead of the project of choice. 

Subpages created for [Zimbabwe ](https://herams-staging.org/project/26/update) and [Chad](https://herams-staging.org/project/15/update) both appear in the dashboard for Nigeria. 

![image](https://user-images.githubusercontent.com/18245059/63940628-30779c00-ca6a-11e9-8aaa-30a82c00fdda.png)

**Comment by SamMousa** [comment]
This should be fixed now.

**Comment by luna404** [comment]
I tested it for Zimbabwe  and CAR. Seems to be working now.
