### ISSUE TITLE
Parent Id not loaded when editing a page

### ISSUE THREAD

**Issue by luna404** [WorldHealthOrganization/herams-backend#205]
If you edit a sub-page, the parent id defaults back to 'No parent'.

![image](https://user-images.githubusercontent.com/18245059/63946564-9b7aa000-ca75-11e9-9e28-bb98b26b9cd1.png)

![image](https://user-images.githubusercontent.com/18245059/63946612-ab927f80-ca75-11e9-8677-a37f9686bbeb.png)

**Comment by SamMousa** [comment]
Same underlying issue as #203. Fixed now

**Comment by luna404** [comment]
Tested - issue is fixed.
