### ISSUE TITLE
Presence of an empty page named "Test" (parent_id=1 & page_id=86) in the HeRAMS NGA Overview

### ISSUE THREAD

**Issue by JeffDotingco** [WorldHealthOrganization/herams-backend#209]
Presence of an empty page named "Test" (parent_id=1 & page_id=86) in the HeRAMS NGA  Overview. I already checked the sorting of other pages. This affects going to the Overview Page from other pages of the dashboard. 

<img width="1680" alt="Screen Shot 2019-09-04 at 1 13 13 AM" src="https://user-images.githubusercontent.com/50957748/64194931-d3894500-ceb2-11e9-8475-0f42a8273890.png">
<img width="1680" alt="Screen Shot 2019-09-04 at 1 06 04 AM" src="https://user-images.githubusercontent.com/50957748/64195014-02072000-ceb3-11e9-9fee-de3c3bc0a866.png">

**Comment by luna404** [comment]
@Jeff this is a result of the issue we had with all sub-pages appearing in the Nigeria dash board. It's a page I create I think in the Chad project. I will delete the page, this should solve the issue

**Comment by JeffDotingco** [comment]
Thanks @luna404

**Comment by luna404** [comment]
I removed the page.
