### ISSUE TITLE
Projects layer API

### ISSUE THREAD

**Issue by SamuelPetragallo** [WorldHealthOrganization/herams-backend#211]
As we are discussing way of improving the visibility of our work, thought we should investigate the feasibility of pushing our "projects layer information (project/country name, x/y coordinates, #HFs, #contributors, latest update)" to the emergency dashboard in house where information is centralized for senior management.

Those could all come in with a link to the actual project on www.herams.org

Any thoughts on the overall idea? 
Any thoughts on feasibility?

Thanks!

**Comment by SamuelPetragallo** [comment]
@SamMousa have you had time to think about this and a sense of the time required to implement? Thanks!

**Comment by SamMousa** [comment]
I have not thought about it since it's clearly defined.
If we're pushing then we need to know their API... If they are pulling it makes sense to check with them first.

**Comment by SamuelPetragallo** [comment]
So here we are: preferred option from their side is pulling data - preferred format: GeoJSON.

What we want to be sharing is:
1. project name, 
2. project x/y coordinates
3. #HFs
4. #contributors
5. date of latest update
6. project URL

No urgency as they may not be able to implement that before end pf October, but the sooner we get it out of our hands the better + we can then discuss graphical representation of those metrics

**Comment by SamuelPetragallo** [comment]
@SamMousa  

First iteration: URL to pull GeoJSON from with 

1. project name
2. project x/y coordinates
6. project URL

**Comment by SamuelPetragallo** [comment]
@SamMousa : can we have a description of the API (even if not active yet)? This would essentially allow me inform IMT of what is coming (and avoid yet another physical meeting where not much else is to be said) - thanks!

**Comment by SamuelPetragallo** [comment]
@SamMousa I don't recall what we said about this last Tuesday.
Is this usable yet or not? I'll be meeting with IMT on this Thursday am next week - if not operational yet but "fixable" by friday next week (second upcoming release) I would probably postpone the meeting, thanks!

**Comment by SamMousa** [comment]
The documentation is available here: https://stoplight.io/p/docs/gh/worldhealthorganization/herams-backend/reference/herams/openapi.yaml/paths/~1projects/get

But implementing it is a waste of time until they can confirm they can and actually will use it

**Comment by SamuelPetragallo** [comment]
Yes they want to start pulling/displaying data and although this has been a slow process we will definitely get there. That dashboard is centralizing information on all sorts of projects in the emergency program here.

I guess they would want to be able to already read/test it, is that something we can add to the upcoming release?

**Comment by SamMousa** [comment]
This is a test URL:
https://herams-staging.org/api/projects

Please inspect it visually.

**Comment by SamuelPetragallo** [comment]
All good except I don't see the "project name" there

**Comment by SamMousa** [comment]
try again!

**Comment by SamuelPetragallo** [comment]
Project 27 / Comoros has 4 WSs and 7 users with edit rights on WS 891 (https://herams-staging.org/workspace/891/share), but displays only 4 contributors in the project metrics and API

**Comment by SamMousa** [comment]
It counts users with `write` and `admin` permissions. There are no users with these permissions so it uses the workspace count.
Do we need it to include `edit data` permission too?

**Comment by SamuelPetragallo** [comment]
Yes please include "Edit" in the count

**Comment by SamuelPetragallo** [comment]
Actually think we could consider any rights (as simple view rights (in the future) will also allow users to contest data and hence contribute)

**Comment by SamMousa** [comment]
View is unlikely to be given per individual workspace though?

**Comment by SamuelPetragallo** [comment]
Was thinking of the ability of users to view responses of a given WS, but that would come later (after we've implemented the HF layer in HeRAMS) / not relevant here

**Comment by SamMousa** [comment]
Anyway, have implemented it now. if you confirm i'll push the release.
