### ISSUE TITLE
Dashboard standards

### ISSUE THREAD

**Issue by luna404** [WorldHealthOrganization/herams-backend#212]
I put together a document to help us standardize the dashboards. It includes an overview on the standard pages, page layouts and proposes a standard color scheme (#206). It's not intended as a final document but something to get the discussion going :). Please comment either here or directly in the document on Google Drive.

[HeRAMS Dashboard Standards](https://drive.google.com/file/d/147kqXIsyqolHahGjMJEPjBW8u4Mpphni/view?usp=sharing)

**Comment by luna404** [comment]
@JeffDotingco I tried to find a compromise for the diverging ("good" to "bad") color scheme. The proposed color scheme is colorblind friendly and also use a green to red gradient.

**Comment by JeffDotingco** [comment]
Okay @luna404, thanks for the document provided and check / apply the colors to the dashboard.

**Comment by JeffDotingco** [comment]
Standard map layout I think is 2x2. The 2x1 is a bit small

**Comment by JeffDotingco** [comment]
The default size for the map I think is 2x2, the 2x1 is a bit small.

**Comment by luna404** [comment]
@JeffDotingco Thanks, you're absolutely right. I'll update this later this afternoon. It will also affect the standard layout of the pages

**Comment by SamuelPetragallo** [comment]
Agree on both comments - nice to have bigger map but may affect overall layout. Could we have an example for both options and choose from there? Thanks!

**Comment by JeffDotingco** [comment]
Standard 2x2 map for the Overview of HeRAMS NGA:
<img width="1680" alt="Screen Shot 2019-09-09 at 10 41 17 PM" src="https://user-images.githubusercontent.com/50957748/64541300-374cbb80-d354-11e9-97e2-17c39575f3fb.png">

2x3 map (as an option that will move table (reasons of unavailability below the chart on health service availability, instead of being below the map if we use 2x2)
<img width="1680" alt="Screen Shot 2019-09-09 at 10 42 07 PM" src="https://user-images.githubusercontent.com/50957748/64541387-5d725b80-d354-11e9-8260-944c95aab536.png">

**Comment by luna404** [comment]
I like the 2x3 options.

What do you think of the map colors? They appear very dark to me. Should we make them a little brighter?

**Comment by luna404** [comment]
I made some changes to the BA colors to add an option for "Not available" for Nigeria and other projects that still use the old format. Alternatively, we could use another shade of grey for these (like it is currently done on PROD).

I also think I was a little overenthusiastic arranging the colors. Looking at the charts with the proposed colors, I think it might be better if we used them in sequential order. 


![image](https://user-images.githubusercontent.com/18245059/64627780-8b0ce280-d3f0-11e9-9122-a3522caf0317.png)

**Comment by JeffDotingco** [comment]
Thanks @luna404 for this! :) Suggestion of also putting the colors for HF type in sequential order from the colors provided in the table.

**Comment by JeffDotingco** [comment]
Thanks @luna404 for this! :) I also have a suggestion of also putting the colors for HF type in sequential order from the colors provided in the table.

**Comment by luna404** [comment]
I didn't do this, because I feel like the difference between the shades is relatively small. So if we only have two categories for example, we can improve the difference by not selecting closet shade.

![image](https://user-images.githubusercontent.com/18245059/64677565-1aa9a400-d478-11e9-8dcf-e25befbc7863.png)

What do you think of keeping the order of selecting additional colors but ordering them sequential? 

![image](https://user-images.githubusercontent.com/18245059/64677894-bfc47c80-d478-11e9-9472-5a37ccbcb48f.png)

![image](https://user-images.githubusercontent.com/18245059/64678013-fb5f4680-d478-11e9-84a9-5960dc73b080.png)

**Comment by JeffDotingco** [comment]
Thanks @luna404. I agree with the previous colors and making them sequential.

**Comment by SamuelPetragallo** [comment]
Regarding "non-standard" approaches: we did look at realigning the outliers such as Nigeria to the standard - not sure where we are on this?

I know NGA is about to do another round of data - would be good to realign as much as possible. Let's try to sit and look at these outliers and decide on realignement

**Comment by JeffDotingco** [comment]
Okay @SamuelPetragallo. The realignment was already initiated with HeRAMS Nigeria 2 (New SDM format) (ID 391149) but not yet on Basic Amenities part. This is also related to #170
