### ISSUE TITLE
Button to return to the dashboard

### ISSUE THREAD

**Issue by luna404** [WorldHealthOrganization/herams-backend#214]
Would it be possible to have a button that allows users to return to the dashboard on the element settings page. If you open the settings page of a dashboard element from within the dashboard, there is currently no option to return to the dashboard except for using the browser's native back buttons. We currently circumvent this by having the dashboard open in two tabs, but it would be much more user-friendly if users can return to the dashboard and immediately view their changes.

**Comment by SamMousa** [comment]
Changes are now shown live.

**Comment by SamMousa** [comment]
What about this? 
![image](https://user-images.githubusercontent.com/547021/66485274-d6c2b280-eaa8-11e9-9b38-7e03ed57ca2d.png)

**Comment by luna404** [comment]
Generally works fine, but there seems to be small issue with the two update buttons. They only work for me on the second click. 

![Oct 18 2019 3_24 PM](https://user-images.githubusercontent.com/18245059/67098418-76c0c000-f1bc-11e9-9b4a-7875f513f071.gif)

**Comment by SamuelPetragallo** [comment]
@SamMousa can you please check this minor issue still so we can close/release (or do you want another issue created for that)?
