### ISSUE TITLE
Improve map zoom level

### ISSUE THREAD

**Issue by luna404** [WorldHealthOrganization/herams-backend#215]
@SamMousa how are you defining the default map zoom level for maps in the dashbaords. It seems like the zoom level is not always optimal and we "loose" significant space to show areas that are not relevant. 

If not already implemented, would it be possible to define zoom level based on the bounding box geometry? I tried to illustrate the difference using Zimbabwe data below. 

Here is the map from the dashboard.

![image](https://user-images.githubusercontent.com/18245059/64547065-238d5f00-d32c-11e9-90a5-c8b09bcc0661.png)

Below is a map using the fitBounds function to define the zoom level. (The points displayed reflect the smallest and largest lat/longs for Zimbabwe). 

![image](https://user-images.githubusercontent.com/18245059/64546977-f5a81a80-d32b-11e9-8b74-9f25d4b90fea.png)

 ```
var locations = [
		["l1",-21.25013833, 32.3930866],
		["l2",-19.5322461, 32.68622666],
		["l3",-20.06376, 32.08561117],
		["l4",-19.79044667, 32.95139833],
		["l5",-20.06376, 32.08561117]
		];

	var map = L.map('mapid').setView([-20.06376, 32.08561117], 7);

	L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw', {
		maxZoom: 18,
		attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, ' +
			'<a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, ' +
			'Imagery © <a href="http://mapbox.com">Mapbox</a>',
		id: 'mapbox.streets'
	}).addTo(map);
	
	var ary = [];
	for (var i = 0; i < locations.length; i++) {
			marker = new L.marker([locations[i][1],locations[i][2]])
				.bindPopup(locations[i][0])
			ary.push(marker)
		}
	lyr = L.featureGroup(ary).addTo(map);
	map.fitBounds(lyr.getBounds());
```

**Comment by SamMousa** [comment]
https://github.com/WorldHealthOrganization/herams-backend/blob/master/protected/widgets/map/DashboardMap.php

**Comment by SamMousa** [comment]
Could be the padding

**Comment by luna404** [comment]
I agree, setting the padding to 0 or remove it completely should improve the default map zoom.

**Comment by SamMousa** [comment]
Padding was an explicit request by @petragallos

**Comment by SamuelPetragallo** [comment]
I'm fine removing padding - and agree overall map zoom can be improved merci!

**Comment by luna404** [comment]
There seems to still be some difference depending on map height. If you compare the two examples below it seems like the zoom is not ideal if the map has a height of 2. Do you think it would be possible to optimize this or should we use the map height to address this?

Size = 2 x 2

![image](https://user-images.githubusercontent.com/18245059/65241094-0baf9b00-dae3-11e9-900a-4e76c6fddc23.png)


Size = 2 x 3
![image](https://user-images.githubusercontent.com/18245059/65240826-76140b80-dae2-11e9-93f0-9d262026c138.png)

**Comment by SamMousa** [comment]
Please add the links to these pages so that I can have a look

**Comment by SamMousa** [comment]
![image](https://user-images.githubusercontent.com/547021/65249628-951b9900-daf4-11e9-98f9-f5448ddba048.png)
I think this is a css cache issue. The padding is set to 20 instead of 50 and this is what I see.
