### ISSUE TITLE
"Unknown" not updating on preview

### ISSUE THREAD

**Issue by luna404** [WorldHealthOrganization/herams-backend#216]
If you create a new map, "Unknown" in the preview map is showing black instead of the selected color. The issue is only in the preview map, the actual map on the dashboard is correct.

Example: Zimbabwe, HFBA9

![image](https://user-images.githubusercontent.com/18245059/64599187-3bf78b00-d3b9-11e9-8a0d-dea2655a5358.png)

**Comment by SamMousa** [comment]
I've also added live previewing, changing any setting will update the preview!
