### ISSUE TITLE
Change default basemap for all maps

### ISSUE THREAD

**Issue by luna404** [WorldHealthOrganization/herams-backend#217]
Could we change the basemap to a more neutral version that gives more emphasis to the data displayed?

I would propose the Esri Light Grey Canvas. 

https://services.arcgisonline.com/arcgis/rest/services/Canvas/World_Light_Gray_Base/MapServer

**Comment by SamMousa** [comment]
Fine for me; @SamuelPetragallo ?

**Comment by SamuelPetragallo** [comment]
Yes agreed!
