### ISSUE TITLE
Wrong answer options loaded

### ISSUE THREAD

**Issue by luna404** [WorldHealthOrganization/herams-backend#222]
If you create a chart or map with variable HFBA10 the wrong answer options are loaded. The issue only happens in project 18 (Chad). Also, the question is multiple choice question in this project and not ranking like in other projects.

![image](https://user-images.githubusercontent.com/18245059/64791658-50ce4d00-d578-11e9-91ec-69972362bd20.png)

Answer options in LS (https://ls.herams.org/admin/questions/sa/subquestions/surveyid/954572/gid/195/qid/3053)
![image](https://user-images.githubusercontent.com/18245059/64791699-62aff000-d578-11e9-8136-9ce145b50ef5.png)

**Comment by SamuelPetragallo** [comment]
I would suggest we move to ranking as others on this (though there may still be a bug to be looked into)

**Comment by SamMousa** [comment]
Can you check that this happens for all multiple choice questions?

**Comment by luna404** [comment]
I don't have another multiple choice question in this survey. I will re-code it as ranking once they complete the data entry. I will close the issue for now as the recording should be solving the issue.
