### ISSUE TITLE
Health Information Systems / Draft Analysis Framework

### ISSUE THREAD

**Issue by SamuelPetragallo** [WorldHealthOrganization/herams-backend#223]
As discussed this am - I've uploaded the draft HIS Analysis Framework for your review/suggestions.

We will definitely revise/improve this as we do more of those (whether formal or informal).

https://drive.google.com/open?id=1YKxL7tb--WAtUTpUq7ptOXgXu8ynyOa4

**Comment by JeffDotingco** [comment]
Suggestion of reorganising Item 2 for approval, based on WHO document on Framework and Standards for Country Health Information Systems. The components in the HIS analysis framework are:

1. Health information system resources (coordination and leadership, policies, financial and human resources, and infrastructure)
2. Indicators (domains of health information, defining core indicators)
3. Data sources
4. Data management (data storage, ensuring data quality, data processing and compilation)
5. Information products
6. Dissemination and use

Source: Framework and standards for country health information systems / Health Metrics Network, World Health Organization. – 2nd ed. Retrieved from https://www.who.int/healthinfo/country_monitoring_evaluation/who-hmn-framework-standards-chi.pdf
