### ISSUE TITLE
Filtering option seems not to be working in the prod platform 

### ISSUE THREAD

**Issue by JeffDotingco** [WorldHealthOrganization/herams-backend#226]
Filtering option seems not to be working in the production platform. I checked NGA, PHL, VANUATU. Redirected to a "You are not allowed to perform this action" page
<img width="1680" alt="Screen Shot 2019-09-20 at 4 12 47 PM" src="https://user-images.githubusercontent.com/50957748/65310759-9b2b7b80-dbc1-11e9-82e7-0a7be84835f8.png">

**Comment by SamuelPetragallo** [comment]
I confirm - works on staging / not on prod
@SamMousa can you check please?

**Comment by JeffDotingco** [comment]
filtering is not working in staging from my end

**Comment by SamMousa** [comment]
This is a permission issue.

**Comment by SamMousa** [comment]
> I confirm - works on staging / not on prod
> @SamMousa can you check please?

Your issue was different @SamuelPetragallo, out of date library... For you it should be resolved on prod, for Jeff it should be resolved on staging. To fix for everyone will need to test on staging then do another release.

**Comment by SamMousa** [comment]
@JeffDotingco have you tested the fix?

**Comment by JeffDotingco** [comment]
@SamMousa I tried changing the project for HeRAMS NGA again in STAGING now  and I am receiving this report:
<img width="1680" alt="Screen Shot 2019-09-25 at 8 43 18 PM" src="https://user-images.githubusercontent.com/50957748/65601747-3ca53980-dfd5-11e9-90df-53845a4e3d78.png">

**Comment by SamMousa** [comment]
That's a different issue...

**Comment by JeffDotingco** [comment]
Apologies, the filtering is working now. I told that in the meeting that it is already fixed.
