### ISSUE TITLE
Filtering option GEO1 for HeRAMS PHL has a mix of "Region" and Region / Province / Municipality options

### ISSUE THREAD

**Issue by JeffDotingco** [WorldHealthOrganization/herams-backend#227]
Filtering option GEO1 for HeRAMS PHL has a mix of "Region" and "Region / Province / Municipality" options for PROD and STAGING.

1.  I already checked the dataset for GEO1, all have the Region / Province / Municipality responses.
2. I want to check the workspaces in the "import workspaces" for PROD and STAGING but I couldn't input the field for import tokens or WS names. 
<img width="1680" alt="Screen Shot 2019-09-20 at 5 15 31 PM" src="https://user-images.githubusercontent.com/50957748/65315295-6839b580-dbca-11e9-877f-f13bd74a8b72.png">

**Comment by SamMousa** [comment]
What is the issue?

**Comment by JeffDotingco** [comment]
The filter options for GEO1 are a mix of "Region" and "Region / Province / Municipality"

**Comment by JeffDotingco** [comment]
<img width="1680" alt="Screen Shot 2019-09-20 at 5 22 40 PM" src="https://user-images.githubusercontent.com/50957748/65315855-6cb29e00-dbcb-11e9-96cd-9321df90719c.png">
<img width="1680" alt="Screen Shot 2019-09-20 at 5 22 58 PM" src="https://user-images.githubusercontent.com/50957748/65315877-750ad900-dbcb-11e9-9ea5-45da07e05d12.png">

**Comment by SamMousa** [comment]
This is because the value contains `(`, per #199 we are splitting all values and ignoring everything after the `(`.

**Comment by JeffDotingco** [comment]
HeRAMS NGA State / LGA (GEO1) works fine
<img width="1680" alt="Screen Shot 2019-09-20 at 5 32 12 PM" src="https://user-images.githubusercontent.com/50957748/65316531-bea7f380-dbcc-11e9-8fd8-02da2d851e01.png">

**Comment by JeffDotingco** [comment]
Okay @SamMousa
