### ISSUE TITLE
Error in changing the survey form for HeRAMS NGA (In PROD and STAGING)

### ISSUE THREAD

**Issue by JeffDotingco** [WorldHealthOrganization/herams-backend#229]
I want to change the survey form for HeRAMS NGA from "HeRAMS Nigeria (GEO1 updated) (ID 567974)" to "HeRAMS Nigeria 2 (New SDM format) (ID 391149)". This is in preparation for the next round of HeRAMS assessment in NGA this October. After updating the project, I am directed to an error page below:

<img width="1680" alt="Screen Shot 2019-09-23 at 11 03 49 PM" src="https://user-images.githubusercontent.com/50957748/65437484-73a11100-de56-11e9-9e7d-5cc8a2175c41.png">

I am also receiving error report in the STAGING platform:
<img width="1680" alt="Screen Shot 2019-09-23 at 11 00 13 PM" src="https://user-images.githubusercontent.com/50957748/65437518-861b4a80-de56-11e9-81db-1cc4a26b97de.png">

**Comment by SamMousa** [comment]
I'm thinking of removing the feature to change survey ID for a project.
When the survey changes we must:
- Remove all workspaces
- Remove all responses

All we have left is the project and the report. 
Since we can export and import the report I do not see a need for dynamically switching surveys.

**Comment by SamuelPetragallo** [comment]
Ok - makes sense yes now that we are keeping some of the data in herams in addition to WS.

Just a question regarding transferring dashboard config over to the new project: would one need to run two parallel projects while transferring config over or can that config be saved it "outside" of a given project? All in all no big deal I think as that's a rather rare thing to do, just curious :)

**Comment by SamMousa** [comment]
You can export and save  to a text file and import later

**Comment by SamMousa** [comment]
The option to update the survey ID should no longer be there on stagin.
