### ISSUE TITLE
www.herams.org URL to the user guide?

### ISSUE THREAD

**Issue by SamuelPetragallo** [WorldHealthOrganization/herams-backend#230]
Would like to reference the user guide in other documents such as the elearning we are finalizing now and find it not clear to have an URL other than www.herams.org/something (or alike) to share

Can we have a www.herams.org/something ponting to the user guide instead of the current?

(Ideally to be sorted by the end of the week if possible)

**Comment by SamMousa** [comment]
Pick a url, and I can set it up. I suggest https://guide.herams.org

**Comment by SamuelPetragallo** [comment]
Let's go for https://docs.herams.org
