### ISSUE TITLE
Download data per workspace (text or code) in HeRAMS NGA is not working (PROD and STAGING)

### ISSUE THREAD

**Issue by JeffDotingco** [WorldHealthOrganization/herams-backend#231]
Download data per workspace (text or code) in HeRAMS NGA is not working (PROD and STAGING). Directed to a page with "Getting unknown property: prime\models\ar\Workspace::heramsResponses", PROD and STAGING screenshots provided below:
<img width="1680" alt="Screen Shot 2019-09-24 at 11 41 12 PM" src="https://user-images.githubusercontent.com/50957748/65527292-0314f580-df25-11e9-8b3a-db46514c6d1e.png">
<img width="1680" alt="Screen Shot 2019-09-24 at 11 41 35 PM" src="https://user-images.githubusercontent.com/50957748/65527322-0c9e5d80-df25-11e9-841f-0ba7cc4aba53.png">

**Comment by SamMousa** [comment]
Is this working?

**Comment by JeffDotingco** [comment]
Downloading is working @SamMousa. But upon looking at the downloaded data, there seems to be a problem as some of the variables are missing (e.g. id, submit date) and not based on the arrangement of the structure of the questionnaire standard data model. The question on "What are the main reasons (up to 3) that explain the lack of availability?", the responses were combined in one single column. Attached is the excel-converted downloaded data for a WS.
[Adamawa  Demsa.xlsx](https://github.com/WorldHealthOrganization/herams-backend/files/3671901/Adamawa.Demsa.xlsx)

**Comment by SamMousa** [comment]
If cells get combined it's probably user error.

https://www.copytrans.net/support/how-to-open-a-csv-file-in-excel/

Create a new issue if you can't get this working.
