### ISSUE TITLE
Dashboard aggregation issue

### ISSUE THREAD

**Issue by luna404** [WorldHealthOrganization/herams-backend#232]
Project: 27, element 103

https://herams.org/element/103/update

There appears to be an issue with the data aggregation in element 103. 

1. The colors don't match the selected colors (see screenshots).
![image](https://user-images.githubusercontent.com/18245059/65888027-29141d00-e39f-11e9-8204-130ce4d959ee.png)

![image](https://user-images.githubusercontent.com/18245059/65888074-37623900-e39f-11e9-9408-dd93ee64cdc0.png)
2. The count is incorrect. The chart displays 103, but the total number should be 142.

The issue seems to arise because the first two response option are abbreviated, resulting in identical labels. The number of missing records in the charts corresponds to number of records which use the first response option. 

A1: **Eau courante**: à l’intérieur de l’établissement (n = 29)
A2: **Eau courante**: à l’extérieur de l’établissement (n = 39)

I will resolve the issue by changing the labels, but I though I might still be worth putting it here.

**Comment by SamMousa** [comment]
The labels must be unique. Even if we supported non-unique labels it would make no sense for a user since they cannot identify which abbreviated label belongs to which original label.
