### ISSUE TITLE
Data structure of the downloaded data per WS should follow the variable arrangement of the survey questionnaire

### ISSUE THREAD

**Issue by JeffDotingco** [WorldHealthOrganization/herams-backend#233]
The data structure of the downloaded data per workspace should follow the arrangement of the survey questionnaire. Some variables (Response ID, Token, Date submitted, Last page, Start language, Date started, Date last action) and UOID initially located in the data are missing: 

[Adamawa  Demsa.xlsx](https://github.com/WorldHealthOrganization/herams-backend/files/3672048/Adamawa.Demsa.xlsx)

**Comment by SamMousa** [comment]
Did you retry using the guide or not?

**Comment by JeffDotingco** [comment]
I used the link you have provided for combined responses in one single column, but still the same.

**Comment by JeffDotingco** [comment]
Hi @luna404, can you test the downloading of data per WS from your side?

**Comment by luna404** [comment]
Few comments on the data export from my side:

- I agree with @JeffDotingco that the order of the variables should be the same as in LS. Also we need at least some of the system variables. Most importantly the record id, but also the date of update and lastpage to know whether the record is complete.
- What is the rational for combining the answers for ranking questions into a single field? In LS they are in separate columns and for most types of analysis it would be better to have them split into columns too. 
- Also combing multiple questions into a single field results in a different data structure compared to the LS export (used to export all workspaces). Having different formats will make it more difficult to create analysis templates that can be used at the national and sub-national level alike. For example, we already have a request from Chad to decentralize some of the analytics so they can ran them at the province or district level. While part of this can be done directly in the dashboard, some additional analysis are likely to be required. It would therefore be much more practical if the same analysis templates can be used at the national and sub-national level.
Combining them into a single column therefore seems like an unnecessary step.
- I would prefer if all columns are exported. I compared two different workspaces and the number of columns is different. I assume you remove all empty columns. I don't like this for two reasons. 
  - Some user might export multiple worskpaces and merge them in Excel. This becomes a rather tedious task if the order of the columns is not standardized. 
  - From an analysis perspective, no answer is important and should not be removed. Also, we need to to be able to run checks on the data to better understand if questions where systematically skipped etc. For this purpose we need all questions in the export.

**Comment by SamMousa** [comment]
The data set is much smaller when removing empty columns, this in turn makes everything faster.
We are not taking the data set from LS, but instead are taking it from our response cache, this cache uses a different more logical structure.
For example, a multiple choice question is a list of answer codes, and thus is stored as such (since we use it as such as well). This makes reporting fast since we do not need to figure out which columns belong to a question and then check each of the columns.

If you use a table in excel you can get columns by name, instead of depending on column order, this will make your analysis more robust. 

I can check to see if there are more system variables available.

**Comment by luna404** [comment]
My main concern is that the data export at the workspace and project level don't have the same format. 

Suggestion 1: I know it would slow down the data download, but would it be possible to use the LS API instead (export_responses_by_token function)? Downloading of workspace data is only used occasionally. I therefore think time is not the most crucial factor and we could accept the data export function being a little slower if we can get a standardized format instead.

Suggestion 2: If we can have an option to download the data on a project level from the data cache it would solve the issue of having different formats for analysis purposes. In this case, would it be possible to have access to the API to pull data directly into other applications (e.g. R, Python, etc.).

**Comment by SamMousa** [comment]
Suggestion 2 is the way to go in my opinion.

**Comment by SamMousa** [comment]
- [ ] Export based on survey structure instead of data
- [ ] Add project level export

**Comment by luna404** [comment]
System variables required:

- Record id
- Date of update
- Last page

Anything else @JeffDotingco

**Comment by JeffDotingco** [comment]
- UOID

**Comment by SamMousa** [comment]
How is the last page variable used during analysis?

**Comment by luna404** [comment]
You can drop the last page.

**Comment by SamMousa** [comment]
Closing this in favor of #261
