### ISSUE TITLE
Error trying to change account information

### ISSUE THREAD

**Issue by luna404** [WorldHealthOrganization/herams-backend#234]
I tired to update my email address, by accessing my user profile > account. (https://herams.org/user/settings/account)

When I try to change the password or the email address, I keep getting the below error.

![image](https://user-images.githubusercontent.com/18245059/66115555-5ba55c00-e5d1-11e9-9d59-ecb1a88fc0bb.png)

**Comment by luna404** [comment]
I got the following error message when trying to change my email and password on staging.
![image](https://user-images.githubusercontent.com/18245059/66901995-27359500-f000-11e9-9ef6-e2222973d796.png)

**Comment by luna404** [comment]
I tried this again. I can change my password but not my email.

**Comment by SamuelPetragallo** [comment]
I've tried that. Was able to change password and email, but when doing the latter I never received the confirmation message expected ("We will send a confirmation message to this address")

**Comment by luna404** [comment]
Same, everything seems to be working except for changing email.

**Comment by SamMousa** [comment]
I have fixed changing email, this now works. 

FYI: you can use a gmail address with infinite aliases for easy testing; for example:
thisisfake@gmail.com

will also receive mails for:
thisisfake+test@gmail.com
thisisfake+alias@gmail.com
thisisfake+anything@gmail.com

**Comment by luna404** [comment]
It's working for me. I was finally able to get rid of my iMMAP email :)
