### ISSUE TITLE
Data not refreshing automatically 

### ISSUE THREAD

**Issue by luna404** [WorldHealthOrganization/herams-backend#239]
project id = 18 (CHAD)

There appears to be an issue with the data cache. I was trying to figure out why I a got different numbers when exporting the data from LS compared to what is shown in HeRAMs. It seems that all records created after September 28 do not show in HeRAMS. I manually refreshed the data for some workspaces and this solved the issue.

Also, just to clarify, what criteria are you using to exclude records from the dashboards?

**Comment by SamuelPetragallo** [comment]
@luna404 we listed them here: https://github.com/WorldHealthOrganization/herams-backend/wiki/HeRAMS-Systemic-Variables (probably the term is not very clear - feel free to edit as required ;) )

**Comment by SamMousa** [comment]
It seems LS was updating staging twice, instead of staging and PROD..
Can you retry this?

**Comment by luna404** [comment]
There still seems to be an issue with the data updating. I deleted a couple of records in project 18 (Chad) yesterday. The new total in LS is 2029 but on the dashboard it still says 2064.

**Comment by SamMousa** [comment]
Deleting is a different issue. Currently we only push on updates in LS, deletion is done via the response picker. 

That's something for on the todo.
Can you confirm that updating / creating syncs correctly?

**Comment by SamMousa** [comment]
I have confirmed that the update works how are you verifying that it doesn't?

**Comment by luna404** [comment]
I was alerted by the country that they don't see that changes in the data they made on the dashboard.

I tested it myself yesterday. I updated a record in the Mali project and put the coordinates to Geneva. The point is still not showing on the map.

Here is a link to the record: https://herams.org/workspace/5459/limesurvey

**Comment by SamMousa** [comment]
Pff, this was hard to track down!

I think the issue was not with pushing data, but with formatting it.
Questions with subquestions in LS get coded differently when pushed.
So we get this:
```ini
// Push
MoSDGPS_SQ001=4.15
// Pull
MoSDGPS[SQ001]=4.15
```

Working on a fix.

**Comment by SamMousa** [comment]
I have updated this on staging; can someone confirm? :)

**Comment by luna404** [comment]
I test this for coordinates only. It worked if I created a new record or update an existing one, but deleting is not working. Deleting only works after refreshing the workspace.
