### ISSUE TITLE
Bug: random user can see (though not act upon) WS ID374 (HeRAMS NGA)

### ISSUE THREAD

**Issue by SamuelPetragallo** [WorldHealthOrganization/herams-backend#24]
I've impersonated various users wih no access rights (e.g. user ID10372). These users can see WS ID374 in their "MyWS" list - though they can't act upon the WS

**Comment by SamMousa** [comment]
I don't think this is still relevant.

**Comment by SamuelPetragallo** [comment]
Indeed gone
