### ISSUE TITLE
Remove block user functionality

### ISSUE THREAD

**Issue by SamMousa** [WorldHealthOrganization/herams-backend#241]
I propose removing the block user functionality.
Taking away all permissions / deleting the user should suffice.
Since we don't require new registrations to be approved nothing stops blocked users from creating new accounts anyway.

**Comment by SamMousa** [comment]
@luna404 @SamuelPetragallo opinions please :)

**Comment by SamuelPetragallo** [comment]
I've never used it and would indeed delete the user instead most likely. Good with me
