### ISSUE TITLE
Granting permissions

### ISSUE THREAD

**Issue by SamMousa** [WorldHealthOrganization/herams-backend#245]
When granting access to a resource there are some universal rules:
- You cannot grant access you do not have (if you could this would essentially give you full access to the system)

Other rules depend on the business rules, @SamuelPetragallo and I shortly discussed this.
This is my proposal for the business rules:

1. Users with `admin` permission can do anything, including sharing.
2. Users can be explicitly granted the `share` permission.
3. Users with the `share` permission can grant other permissions they have, not the `share` permission itself.

Consider the following story, all about one specific project, project `X`.
1. Jane has `admin` permissions on project `X`.
2. Jane grants `write` and `share` to Bob, allowed by rule 1.
3. There is a business rule: `if you can write a project, you can read it`.
4. Bob grants `read` to Joe, allowed by 3.
5. Bob can not grant `share` to Joe.
6. Joe can not grant his `read` permission to anyone else.

Limitation of this approach is that we cannot have someone delegate sharing.
Consider an organization with department heads:
- The project admin wants to delegate sharing to the organization admin.
- The organization admin wants to delegate sharing to the department heads.

If we need this kind of delegation we have 2 choices:
- Change rule 3, allowing anyone with the `share` permission to grant the `share` permission.
- Introduce another `super_share` permission that allows granting `share` to others.

If we change the rule then it means that anyone who can share, will also be able to delegate sharing.

**Comment by SamMousa** [comment]
@SamuelPetragallo @luna404 your feedback is needed.

**Comment by SamMousa** [comment]
Bump!

**Comment by SamuelPetragallo** [comment]
Thanks for bumping @SamMousa ! We went through it together with @luna404 just now and yes, option 1 is what we need:

1. Users with admin permission can do anything, including sharing
2. Users can be explicitly granted the share permission
3. Users with the share permission can grant other permissions they have, not the share permission itself

Granting of share of permissions at any given level will have to come from the admin at the level above

**Comment by SamMousa** [comment]
Okay clear.
What about revoking?

Could we say that a user could revoke any permission that he could grant?

So if I have permission SHARE + WRITE for project X, I could revoke WRITE permissions for others (since I can also grant that), but not SHARE permissions (since I cannot grant that)?

**Comment by SamuelPetragallo** [comment]
Could we say that a user could revoke any permission that he could grant?

Yes

**Comment by SamMousa** [comment]
Reopened this since #282 indicates that the decision that was made is not correct.

**Comment by SamMousa** [comment]
@luna404 @SamuelPetragallo Super share was implemented as discussed in this thread.
This means the point from the document:

>     2. Without the option to allow everything, we no long have the ability for a workspace owner 
to grant the share permission to other users.

is not valid (and as far as I can tell wasn't valid even before the document was written).
