### ISSUE TITLE
Import workspaces on staging not displaying available tokens

### ISSUE THREAD

**Issue by luna404** [WorldHealthOrganization/herams-backend#248]
I'm having an issue importing workspaces on staging for project 24 (Mali).

On Prod you get a list of available tokens to import.

![image](https://user-images.githubusercontent.com/18245059/68294773-39e83a80-0091-11ea-94e5-65802915481d.png)

This list no longer shows on staging. 
![image](https://user-images.githubusercontent.com/18245059/68295091-e3c7c700-0091-11ea-81ba-f163ecc3cabd.png)

If you look at the total number of workspaces on production and staging, there are currently 76 workspaces in both environments. So in my understanding there should be the same number of tokens available to import on staging.

**Comment by SamMousa** [comment]
For future reference, please add a direct link to the page. This makes finding and confirming it easier for everyone.

https://www.herams-staging.org/workspace/import?project_id=24
