### ISSUE TITLE
Add button to refresh all workspaces 

### ISSUE THREAD

**Issue by luna404** [WorldHealthOrganization/herams-backend#249]
Would it be possible to add a button to the workspace page that refreshes the data cache for all worksapces at once? At the moment we have to refresh each workspace individually. With projects such as the Philippines with over 1000 workspaces, this is no longer feasible.

**Comment by SamMousa** [comment]
The only reason the buttons are there is for debugging / working around issues.
When the issues are fixed these buttons should no longer be necessary at any level.

Adding them to the project level means it can take an hour to refresh, meaning you will get timeouts etc, that simply doesn't work with the current synchronous approach.
