### ISSUE TITLE
Sort workspaces alphabetically

### ISSUE THREAD

**Issue by luna404** [WorldHealthOrganization/herams-backend#250]
Would it be possible to sort workspaces based on the title field rather than the workspace id?

**Comment by SamMousa** [comment]
You can sort individual columns already.
Regarding default sort order I'm leaning towards sorting by most recent update.

Reasoning is as follows:
- If you just changed data that workspace will show at the top
- If you are looking for a specific workspace you can use search.

**Comment by SamMousa** [comment]
Default sort order is now by latest update, descending.
