### ISSUE TITLE
Error in share workspace page because of deleted user account

### ISSUE THREAD

**Issue by luna404** [WorldHealthOrganization/herams-backend#251]
I deleted a user account that was still assigned to a workspace. The missing name is now creating an error when you try to open the share workspace page. 

Error message: `Trying to get property 'name' of non-object`
https://herams.org/workspace/6979/share

**Comment by SamuelPetragallo** [comment]
@luna404 opening that WS now works - can we assume this equates to bug resolved (not sure which user to check with for a proper test)
