### ISSUE TITLE
Internal links don't work in translations

### ISSUE THREAD

**Issue by luna404** [WorldHealthOrganization/herams-backend#252]
Internal links in the user guide are not working in the translations (both French and Arabic) if the displayed text is different from the link itself.

In the base language internal links are referenced as shown below. 

```
* |share-icon| **Share Workspace**: To grant a user access to workspace, the workspace must be shared with the user. For more information on how to add users to a workspace click `here`__.
* |delete-black| **Delete Workspace**: Permanently removes a workspace from a project. See `Delete a Workspace`__ for more information.
* |download| **Download Data**: Downloads all records belonging to the selected workspace. See `Download Data`__ for more information.
* |pencil-black| **Data Update**: This opens the data edit interface. More information on data editing and updating is available `here`__.
  
.. __: `Add a User to a Workspace`_
.. __: `Delete a Workspace`_
.. __: `Download Data`_
.. __: `Edit Data`_`
```
However, in the translations, the link is not properly displayed.
![image](https://user-images.githubusercontent.com/18245059/69524506-7a3b2a00-0f66-11ea-98fd-f83aa4da730c.png)

In order for the translations to display the link correctly I have to include the link in the translation string as shown below

![image](https://user-images.githubusercontent.com/18245059/69525290-187bbf80-0f68-11ea-9367-aa847a1300ec.png)

![image](https://user-images.githubusercontent.com/18245059/69524596-b2426d00-0f66-11ea-9ed4-4928c2013b73.png)

Before we change all the links, is there an easier way to fix the issue?

**Comment by SamMousa** [comment]
There is a way to localize links; I already had an example of that somewhere in the docs. Will see if I can find it again.

**Comment by SamMousa** [comment]
![image](https://user-images.githubusercontent.com/547021/69529101-e53d2e80-0f6f-11ea-8560-d7b5da89b0e3.png)

I think this is the issue you are seeing.

**Comment by luna404** [comment]
Yes, so I will have to change the links :)
