### ISSUE TITLE
Workspace not working on staging

### ISSUE THREAD

**Issue by luna404** [WorldHealthOrganization/herams-backend#257]
The workspace page for all projects with at least one workspace are not working on staging (e.g. https://herams-staging.org/project/13/workspaces)

![image](https://user-images.githubusercontent.com/18245059/70223808-7f5d5d80-174c-11ea-8242-58ba6cdfa154.png)

**Comment by SamMousa** [comment]
Seems the server uses a different database version; anyway, fixed it!
