### ISSUE TITLE
Causes of unavailability chart returns error

### ISSUE THREAD

**Issue by luna404** [WorldHealthOrganization/herams-backend#258]
The causes of unavailability chart and table are not working in project 24 (Mali).

https://herams-staging.org/project/24
https://herams-staging.org/element/822/update

They are still in the early stages of data collection, but they completed about 100 records so there should be some data available for these charts/tables.

**Comment by SamMousa** [comment]
https://ls.herams.org/admin/survey/sa/view/surveyid/996483/gid/440/qid/7935

The question type is wrong, causes must be multiple choice.

**Comment by luna404** [comment]
These questions should not be included in the service availability. Are you including all question codes that start with QHeRAMS? If this is the case we have to make some changes to the SDM and change the question codes for this section.

**Comment by SamMousa** [comment]
> Are you including all question codes that start with QHeRAMS?

Yes, that's the pattern for a service, and the same code with an `x` appended is then for the associated reasons.

**Comment by luna404** [comment]
Ok, thanks we will change the codes for this section.
