### ISSUE TITLE
Mockups - Login

### ISSUE THREAD

**Issue by be-novelt** [WorldHealthOrganization/herams-backend#26]
![herams_login_1](https://user-images.githubusercontent.com/43411015/53649447-74682080-3c42-11e9-8651-376a1bc1ff3a.jpg)
![herams_login_2](https://user-images.githubusercontent.com/43411015/53649448-74682080-3c42-11e9-951e-a4615e31ebe4.jpg)
![herams_login_3](https://user-images.githubusercontent.com/43411015/53649451-7500b700-3c42-11e9-8845-c4ac96595ef6.jpg)

**Comment by SamMousa** [comment]
This map on the background, is it just a world map without any points? (The legend in the bottom right suggests otherwise)..

**Comment by SamMousa** [comment]
Requesting access to a project is not part of the sign in / sign up flow, so doing it in this layout doesn't make sense. The user is already logged in when requesting access.

**Comment by be-novelt** [comment]
It's just a background. The legend should be removed at this step, effectively.

**Comment by SamuelPetragallo** [comment]
> This map on the background, is it just a world map without any points? (The legend in the bottom right suggests otherwise)..

You're right Sam in that there will be no legend anymore: all projects will be represented the same way (whether data is already available accessible will be determind in the project popup). Now, whether we want to have the dots on that map already I don't know. Depends on Bruno's suggestion and whether there are complications to do so technically speaking I guess, I leave it to you both

**Comment by SamuelPetragallo** [comment]
Ok, you guys had already sorted that out actually lol... will read through next thread before I react... :D

**Comment by SamuelPetragallo** [comment]
On access indeed - no access request at this stage, only from the project popups

**Comment by SamMousa** [comment]
@be-novelt we need a location for the users who want to resend their confirmation email.

Could you add it to the mock?

**Comment by SamMousa** [comment]
![image](https://user-images.githubusercontent.com/547021/54215664-98e8b600-44e8-11e9-8da2-cd95d9de9008.png)
@be-novelt feedback please!

**Comment by SamMousa** [comment]
@SamuelPetragallo  please add the text you want on the login and signup pages to this issue

**Comment by SamuelPetragallo** [comment]
Here it is:

The Health Resources and Services Availability Monitoring System is a collaborative process for the monitoring of essential health resources and services in support to the identification of needs, gaps and priorities

**Comment by SamuelPetragallo** [comment]
Beyond the text (above) is that for Bruno and You to check/refine now?

**Comment by SamMousa** [comment]
Yes. Text has been updated.

**Comment by be-novelt** [comment]
Hi Sam, Sorry for my late answer... here is my first feedback >>
![feedback_login](https://user-images.githubusercontent.com/43411015/54419870-bd22dd80-4708-11e9-914d-4fc3f4e85e48.jpg)

**Comment by be-novelt** [comment]
Lot of modifications linked to my mockup about many details... 
Be careful to keep (if possible) my recommandations about fonts, colours and dimensions >> 
![HeRAMs_map_measures_2](https://user-images.githubusercontent.com/43411015/54420107-6cf84b00-4709-11e9-8378-c81906b5f78a.jpg)

**Comment by be-novelt** [comment]
Don't hesitate to ask me more information by Skype or by email if necessary. Thanks

**Comment by SamMousa** [comment]
Can you check the new version? It should be even closer to what you envision.
