### ISSUE TITLE
Token fields in LS

### ISSUE THREAD

**Issue by SamMousa** [WorldHealthOrganization/herams-backend#266]
Which token fields are required in LS?

If I look at some of the surveys I see a lot of different custom fields;
Mozambique has just `WSname`, Nigeria has `ISOCode3` and `State_LGA`

What is the standardization?

**Comment by JeffDotingco** [comment]
Hi @SamMousa, good point on the standardization, it should be WSname. The State_LGA for NGA corresponds to WSname. I will change the name to WSname.

**Comment by SamMousa** [comment]
If that is the only field, do we even need token editing in Herams?

We could just sync the workspace name automatically...

**Comment by SamMousa** [comment]
In Comores there are Region_Province_Municipality and attribute_1

Is there any standardization on this? @SamuelPetragallo?

**Comment by SamuelPetragallo** [comment]
We need to loo into this with @JeffDotingco and @luna404 .

There use to be standardization across, but it may have gone a little wild int he last scale up. We can reconsider with their experience as well and decide the way forward

**Comment by JeffDotingco** [comment]
The attribute title for Comores was an error but it should be WSname. During the configuration, it was decided to use the islands (Territoire) and not the GEO1 (Territoire / Préfecture) because the number of HFs per Territoire / Préfecture was only few.
