### ISSUE TITLE
General settings of a survey not accessible

### ISSUE THREAD

**Issue by SamuelPetragallo** [WorldHealthOrganization/herams-backend#268]
https://ls.herams.org/admin/survey/sa/editsurveysettings/surveyid/418614

Needed rather quickly (i.e. latest moday COB ideally)

**Comment by SamMousa** [comment]
Yes, that's the one that's caused by not having the survey active; activating it should be a workaround.

**Comment by SamMousa** [comment]
Fixed via https://github.com/SAM-IT/ls2-submission/commit/627d68cc942f11e89fc1eab70bf3414bab9b9c77
