### ISSUE TITLE
General settings of HeRAMS Yemen Test Survey (ID 618734) not accessible 

### ISSUE THREAD

**Issue by JeffDotingco** [WorldHealthOrganization/herams-backend#269]
General settings of HeRAMS Yemen Survey (ID 618734) not accessible when dataset and token are uploaded. But it is accessible without the data when activated.
<img width="1680" alt="Screen Shot 2020-01-13 at 7 31 15 PM" src="https://user-images.githubusercontent.com/50957748/72254408-eff67480-363e-11ea-9ecd-45fb05d93eea.png">
<img width="1680" alt="Screen Shot 2020-01-13 at 7 33 48 PM" src="https://user-images.githubusercontent.com/50957748/72254422-f84eaf80-363e-11ea-93ce-a03fa97266a6.png">

**Comment by SamuelPetragallo** [comment]
We just checked Yemen and the bug still applies - but only applies to Yemen it seems (Chad for example works). We need that for the setup - I'll put a milestone to it

**Comment by SamMousa** [comment]
Yes, the workaround is to activate the survey; it is a bug in the submission plugin.

**Comment by SamuelPetragallo** [comment]
The survey is activated

**Comment by SamMousa** [comment]
Try again i've increased the memory limit (there are 2 issues at play here)

**Comment by SamuelPetragallo** [comment]
Works now, thanks @SamMousa ! Up to you how/if you want to classify that. Not sure if/what needs to be looked at beyond memory
