### ISSUE TITLE
Mockups - Map with left menu

### ISSUE THREAD

**Issue by be-novelt** [WorldHealthOrganization/herams-backend#27]
![herams_map_1](https://user-images.githubusercontent.com/43411015/53651594-3faa9800-3c47-11e9-93b5-87871575ba04.jpg)
![herams_map_1bis](https://user-images.githubusercontent.com/43411015/53651595-3faa9800-3c47-11e9-878c-22a46993858a.jpg)
![herams_map_2](https://user-images.githubusercontent.com/43411015/53651596-3faa9800-3c47-11e9-8af7-2c6fa94320f7.jpg)
![herams_map_2bis](https://user-images.githubusercontent.com/43411015/53651597-40432e80-3c47-11e9-804e-8a1364efa37b.jpg)

**Comment by SamuelPetragallo** [comment]
Beautiful Bruno! Thanks!

Only comment for me is: no need for the left menu to be collapsible (seonc screen).  There's not much to the map beyond being an entry point to projects and giving an overview of HeRAMS globally, both for which the available space is way enough

**Comment by be-novelt** [comment]
Ok, as you want. On this screen, the intro text (of the login) has been removed. Do you want an icon to show it ? (About Herams for exemple, next to Partners)

**Comment by SamuelPetragallo** [comment]
Yes that would be great definitely!

**Comment by SamuelPetragallo** [comment]
Additionnal question here: would it be possible here to have the last update for the project displayed together with the 2 other metrics? (eventually at the bottom as we've done previously?)
