### ISSUE TITLE
Some HeRAMS users get an error when trying to access ls

### ISSUE THREAD

**Issue by SamuelPetragallo** [WorldHealthOrganization/herams-backend#272]
Note: doesn't apply to all users: I can, Jeremie (11079) and our Test User (10671) can't for example

The error message was around the default language of the user. Strangely, the bug (?) doesn't seem to be systematic. So I'll keep this bug on "standby" for now in case it reproduces (@jeremiehelme keep us posted if that's the case and please share a copy of the error message here or anything else that may help)

**Comment by jeremiehelme** [comment]
It happens every time I visit https://herams.org/admin/limesurvey for the first time.
If I refresh the page it loads fine 

Here is the beginning of the error :
![Capture d’écran 2020-01-16 à 15 31 41](https://user-images.githubusercontent.com/2345926/72533402-67154e00-3875-11ea-8d1a-9ea97497b7b8.png)

**Comment by SamMousa** [comment]
This is because 've turned debugging on to debug some other errors.
Note that turning debug off will hide the above error, but doesn't actually fix it.
@SamuelPetragallo this is one more sign that the (version of) LS we are using should be phased out sooner rather than later.

**Comment by SamMousa** [comment]
I have disabled the debug mode; if that resolves the issue for now, please close this!
