### ISSUE TITLE
Popover layout for errors

### ISSUE THREAD

**Issue by jeremiehelme** [WorldHealthOrganization/herams-backend#273]
In the mockup, the layout for the error popover is a bit different than the one for the login
The description on the left is removed.

Login :
![HeRAMs_login_1](https://user-images.githubusercontent.com/2345926/72514308-b85e1700-384e-11ea-9e26-ed31927b3485.jpg)

Error :
![Herams_ErrorPage_1](https://user-images.githubusercontent.com/2345926/72514248-9fedfc80-384e-11ea-8230-87217b673177.jpg)

We could either create a specific template, or just add a CSS class to the popover, so I can change the grid layout ?

**Comment by SamMousa** [comment]
Let's use a different layout, keeps it clean and simple.

**Comment by jeremiehelme** [comment]
Ok thanks,

I duplicated the map-popover layout and made the changes

It's in the pull request :
https://github.com/WorldHealthOrganization/herams-backend/pull/274

**Comment by SamMousa** [comment]
Merged!
