### ISSUE TITLE
Admin privileges cancelled following user delete / staging

### ISSUE THREAD

**Issue by SamuelPetragallo** [WorldHealthOrganization/herams-backend#276]
@luna404 deleted the test user account to check if this still caused an issue with workspaces being locked (#251). That worked but it also resulted in her - as well as my (?) - admin privileges on staging "disappearing"

**Comment by SamMousa** [comment]
Seems all permissions are gone; will need some more time to research.

**Comment by SamuelPetragallo** [comment]
Yes that's what it looks like, thanks for taking it up! Just to be sure, would that happen on prod for bad testing we could roll-it back right?

**Comment by SamMousa** [comment]
On prod I'll make a backup of the database before applying the update.

**Comment by SamMousa** [comment]
This has been resolved; there was indeed an issue that caused all permissions to be cleared when a user was deleted.
