### ISSUE TITLE
Error in getting access to backend administration and display token button in production

### ISSUE THREAD

**Issue by JeffDotingco** [WorldHealthOrganization/herams-backend#277]
1. Error in getting access if you click backend administration in production. Error is resolved when you double click it again
2. Error when you click "display tokens" in production.
<img width="1680" alt="Screen Shot 2020-01-18 at 6 54 36 PM" src="https://user-images.githubusercontent.com/50957748/72662630-49d2b200-3a24-11ea-8dd4-06d8b63bd0d3.png">
<img width="1680" alt="Screen Shot 2020-01-18 at 6 51 29 PM" src="https://user-images.githubusercontent.com/50957748/72662641-61119f80-3a24-11ea-8423-bcb95f3deab9.png">

**Comment by SamMousa** [comment]
This is a consequence of me enabling debug mode (to do testing for the other bugs); i have disabled it again.
