### ISSUE TITLE
Measurements > Map + Left menu + Login

### ISSUE THREAD

**Issue by be-novelt** [WorldHealthOrganization/herams-backend#28]
![herams_map_measures](https://user-images.githubusercontent.com/43411015/53656182-c4e77a00-3c52-11e9-9b7b-c748b16ad320.jpg)

**Comment by SamuelPetragallo** [comment]
That looks neaaaat thanks! (Yes, I've gone a little overboard with the apero... :p )

**Comment by be-novelt** [comment]
![herams_map_measures_2](https://user-images.githubusercontent.com/43411015/53699963-dadd7200-3ded-11e9-823f-9f66c12316f8.jpg)
![herams_map_measures_3](https://user-images.githubusercontent.com/43411015/53699964-dadd7200-3ded-11e9-998c-13ee2a964dad.jpg)
