### ISSUE TITLE
Role: Workspace Owner

### ISSUE THREAD

**Issue by SamMousa** [WorldHealthOrganization/herams-backend#280]
This issue is to test workspace owner permissions.

- [x] Can edit data in the WS
- [x] Can download data in the WS
- [x] Can share WS to others, specifically Data & Export permission.
- [x] Can unshare WS, specifically Data & Export permission.
- [x] Can only view project dashboard

**Comment by SamMousa** [comment]
@JeffDotingco, I have created a user called **Workspace Owner**, please confirm that it works as expected. I have checked all items listed above.

**Comment by SamMousa** [comment]
Okay so this all works?

Note that the format of data is not related to permissions so it is not relevant here.

**Comment by JeffDotingco** [comment]
yes @SamMousa
