### ISSUE TITLE
Role: Project Owner

### ISSUE THREAD

**Issue by SamMousa** [WorldHealthOrganization/herams-backend#281]
This issue is to test project owner permissions.

- [ ] Can view WS
- [ ] Cannot download data
- [ ] Can share project to others specifically read
- [ ] Can share workspaces in the project to others with read permission 
- [ ] Can unshare project, specifically read permission.
- [ ] Can unshare workspaces in the project, specifically read permission
- [ ] Can only view project dashboard

### Sharing a workspace while being a project owner
When sharing a workspace there is an issue: while a project owner technically has permissions to share a workspace (because he can share the project it belongs to), he cannot actually give any permissions.
The reason for this is that there is no viewing individual workspaces and thus no read permission. If the project owner however has, for example, export permission on a single workspace, he will be able to share that.
It is hard to filter this in advance since we would have to check for every possible permission for each workspace.

@SamuelPetragallo what I could do is when you try to share a workspace (at which time I do check all possible permissions to see if you could actually give them) redirect you back to the previous page and show a message that there are now permissions that you can share with anyone.
It is still not ideal, but at least won't cause validation errors that we cannot get past. (We are essentially showing the user an empty list and then telling them that they should select at least 1 option...)

**Comment by SamMousa** [comment]
I have implemented my proposal, and it looks like this:
![image](https://user-images.githubusercontent.com/547021/72819788-29963380-3c6e-11ea-8349-90a495069b91.png)


It is not ideal but a compromise between performance and user experience...

**Comment by JeffDotingco** [comment]
| Permissions | Status | Remarks
|--------|----------|----------|  
|Can view WS | working 
|Cannot download data | working 
|Can share project to others specifically read | working | can share "Read, this grants access to the dashboard" permission
|Can share workspaces in the project to others with read permission | not working | "Error! There are no permissions that you can share for this workspace"
|Can unshare project, specifically read permission | working 
|Can unshare workspaces in the project, specifically read permission | no yet tested 
|Can only view project dashboard | working

**Comment by SamMousa** [comment]
@JeffDotingco I think it works as intended, just scroll up and read the description.

**Comment by SamuelPetragallo** [comment]
> This issue is to test project owner permissions.
> 
> * [ ]  Can view WS
> * [ ]  Cannot download data
> * [ ]  Can share project to others specifically read
> * [ ]  Can share workspaces in the project to others with read permission
> * [ ]  Can unshare project, specifically read permission.
> * [ ]  Can unshare workspaces in the project, specifically read permission
> * [ ]  Can only view project dashboard
> 
> ### Sharing a workspace while being a project owner
> When sharing a workspace there is an issue: while a project owner technically has permissions to share a workspace (because he can share the project it belongs to), he cannot actually give any permissions.
> The reason for this is that there is no viewing individual workspaces and thus no read permission. If the project owner however has, for example, export permission on a single workspace, he will be able to share that.
> It is hard to filter this in advance since we would have to check for every possible permission for each workspace.
> 
> @SamuelPetragallo what I could do is when you try to share a workspace (at which time I do check all possible permissions to see if you could actually give them) redirect you back to the previous page and show a message that there are now permissions that you can share with anyone.
> It is still not ideal, but at least won't cause validation errors that we cannot get past. (We are essentially showing the user an empty list and then telling them that they should select at least 1 option...)



> I have implemented my proposal, and it looks like this:
> ![image](https://user-images.githubusercontent.com/547021/72819788-29963380-3c6e-11ea-8349-90a495069b91.png)
> 
> It is not ideal but a compromise between performance and user experience...

Yes @SamMousa that works for us thanks!

**Comment by SamMousa** [comment]
@luna404 please double check, the things you mentioned in your word document don't align with what was concluded in this issue.
To repeat: 
This is the setup:
![image](https://user-images.githubusercontent.com/547021/73463867-458c8a00-437e-11ea-86f6-74bda8ede8bf.png)

To confirm, impersonate the `Workspace Owner` user and go to this page: https://herams-staging.org/project/28/workspaces?sort=-id

**Comment by luna404** [comment]
Project owners and workspace owner have no connections in terms of permissions. The above workspace owner permissions are correct. Where does this contradict the Word document?

**Comment by SamMousa** [comment]
I think it was about "viewing a workspace"  which is not a thing in the current platform.  
If you're happy with how it currently works then I have no issues here :)
