### ISSUE TITLE
Add new role: Data Viewer

### ISSUE THREAD

**Issue by luna404** [WorldHealthOrganization/herams-backend#283]
I had a request from Burkina Faso yesterday for a role that permits to view data but not editing it. As downloading is already a separate permission, would it be possible to add another role that only permits to download data at the workspace level?

**Comment by SamMousa** [comment]
It doesn't make sense to have a role that has just 1 permission; just assign them the specific permission instead?

**Comment by luna404** [comment]
Sure. I though we the ability to assign individual permissions was only temporary and that we would only be able to assign roles. But if we continue to be able to assign individual permissions that would solve my issue.

**Comment by SamMousa** [comment]
We will have both
