### ISSUE TITLE
PDF version of HeRAMS Platform User Guide Arabic version download icon 

### ISSUE THREAD

**Issue by JeffDotingco** [WorldHealthOrganization/herams-backend#286]
Support for the creation of a PDF version of HeRAMS Platform User Guide (Arabic version) download icon to be available. WCO YEM asked for support for the pdf to be a full-page text of the guide just like the English version. The current Arabic PDF is half-page text.
[المقدمة — HeRAMS documentation.pdf](https://github.com/WorldHealthOrganization/herams-backend/files/4103116/HeRAMS.documentation.pdf)

**Comment by SamMousa** [comment]
This has been implemented, might take a while before it is visible.
