### ISSUE TITLE
Issue importing tokens on staging

### ISSUE THREAD

**Issue by luna404** [WorldHealthOrganization/herams-backend#289]
I'm trying to create a test project on staging, but when importing the tokens I get the below error. I tried changing the attribute field name but it's not solving the issue. 

https://herams-staging.org/workspace/import?project_id=38

![image](https://user-images.githubusercontent.com/18245059/73160773-2bd31480-40ea-11ea-95dd-62819c699a3c.png)

**Comment by SamMousa** [comment]
Try adding / removing a field; this has to do with the way LS stores the fields.

**Comment by luna404** [comment]
I tried recreating the token table, delete fields, add fields, rename fields. Nothing seems to solve the error.

**Comment by SamMousa** [comment]
Ah, actually it did fix the issue, but the old incorrect structure is still cached.

I have flushed the cache and it works now. 
Don't close this, I'll add a fix that clears the cache when this error occurs!

**Comment by luna404** [comment]
Thanks!

**Comment by SamMousa** [comment]
The fix for this is now live; that means that when it happens again the cache will be cleared and recreating the token table will fix the issue.
