### ISSUE TITLE
Sign up

### ISSUE THREAD

**Issue by SamMousa** [WorldHealthOrganization/herams-backend#29]
Remove non required fields from sign up so users can register faster.

We should only ask for the bare minimum on sign up.

**Comment by SamMousa** [comment]
- [ ] @SamuelPetragallo should define which fields are the bare minimum
- [ ] @SamMousa should hide all other fields.

**Comment by SamuelPetragallo** [comment]
Could we keep the ones we have - but make them non mandatory (apart from the first block down to email)?

**Comment by SamMousa** [comment]
+ name & password :)

**Comment by SamMousa** [comment]
https://herams-staging.org/user/register
