### ISSUE TITLE
Support for the default page of HeRAMS YEM questionnaire to be the welcome page with the language switch

### ISSUE THREAD

**Issue by JeffDotingco** [WorldHealthOrganization/herams-backend#290]
WCO YEM made a comment regarding the default language of HeRAMS YEM questionnaire: "You can't "Select the Arabic Language" in the questionnaire (i.e. you have to update/edit the questionnaire in English for the 1st time. Then when you close and edit/update the HF for the 2nd time you can select the language)"

- I checked this one and the remedy upon checking is select the "previous" icon to be redirected to the welcome page where the language switch is located (Arabic or English)

Is there a way that the default page for edit / update response is the welcome page so that they can select the language?

**Comment by jeremiehelme** [comment]
From what I see in the LS template, there were a language switch at the top of each question that has been hidden.
Making it visible again, at least for the first question, would solve the problem ? 

I have to test on a questionnaire with multiple languages first

**Comment by JeffDotingco** [comment]
Thanks @jeremiehelme ! Already fixed in the HeRAMS YEM by changing the language in the tokens table. From the meeting discussion, the language switch should appear in all the pages of the questionnaire. It is currently just located in the welcome page.

**Comment by JeffDotingco** [comment]
Caroline already showed me the template you are working on for the language switch on top of every page! That would be helpful!
