### ISSUE TITLE
Error view token table in LS

### ISSUE THREAD

**Issue by luna404** [WorldHealthOrganization/herams-backend#300]
I can't access the token tables in LS. I tried several surveys but I keep getting the same error for all of them. 

https://ls.herams.org/admin/tokens/sa/browse/surveyid/341175

![image](https://user-images.githubusercontent.com/18245059/73745062-6f64f880-4752-11ea-9dce-4d025a527afd.png)

**Comment by SamMousa** [comment]
Try now!

**Comment by luna404** [comment]
thanks, it's working again.
