### ISSUE TITLE
New Permission labels

### ISSUE THREAD

**Issue by luna404** [WorldHealthOrganization/herams-backend#304]
Below are the suggested new permission label and order. If it's not too much work, I think it would be could to complement the label with the corresponding icon used in the action column .  For example :

![image](https://user-images.githubusercontent.com/18245059/74042137-426d4b80-49c7-11ea-9eb4-7c4e0bf0bbde.png)

**Project level**

| Current name 	| New name 	|
|---------------	|---------------|
| Read, this grants access to the dashboard 	| View project dashboard	|
| Manage data in LimeSurvey 	| Edit project data 	|
| Export, allows exporting data 	| Download project data 	|
| Manage workspaces in the project 	| Manage project workspaces	|
| Manage dashboards in the project 	| Configure project dashboard 	|
| Write, this grants access to properties 	| Edit project settings 	|
| Share, allows users to give other users limited access 	| Manage project users 	|
| Super share, allows this user to give other users the share permission 	| Grant project admin permissions	|

**Workspace level**

| Current name 	| New name 	|
|---------------	|---------------|
| Manage data in LimeSurvey 	| Edit workspace data 	|
| Export, allows exporting data 	| Download workspace data 	|
| Share, allows users to give other users limited access 	| Manage workspace users 	|
| Super share, allows this user to give other users the share permission 	| Grant workspace admin permissions 	|

**Comment by SamMousa** [comment]
![image](https://user-images.githubusercontent.com/547021/75245099-5b4e6d00-57cd-11ea-8cfb-c3b1afc340ff.png)

**Comment by SamMousa** [comment]
![image](https://user-images.githubusercontent.com/547021/75245156-76b97800-57cd-11ea-84ba-819b05bf4b79.png)

**Comment by JeffDotingco** [comment]
Error when you click project-level sharing icon in PROD
<img width="1680" alt="Screen Shot 2020-02-28 at 9 39 34 PM" src="https://user-images.githubusercontent.com/50957748/75553224-ebf9a700-5a72-11ea-8316-ea1de6f08a1e.png">

**Comment by SamMousa** [comment]
Does this work on staging?

**Comment by JeffDotingco** [comment]
Yes, project and workspace level sharing works in staging

**Comment by SamMousa** [comment]
Fixed it now.

**Comment by JeffDotingco** [comment]
confirmed, working in PROD
