### ISSUE TITLE
Loading main.css for every screen

### ISSUE THREAD

**Issue by jeremiehelme** [WorldHealthOrganization/herams-backend#309]
If the purpose of main.css is to contain CSS declarations useful for every screen, could we load it globally ? So far it's only loaded for some screens (AppAsset and NewAppAsset Bundles)

**Comment by SamMousa** [comment]
It is loaded via those bundles, but on which screens is it not loaded / loaded?

**Comment by jeremiehelme** [comment]
For the project screen for example :
https://herams-staging.org/project/28

**Comment by SamMousa** [comment]
Yes, makes sense to me; you can add `main.css` to the `DashboardBundle` and it should take care of that.

Alternatively you could create a new `MainBundle` and make both `DashboardBundle` and `NewAppAsset` depend on it.
