### ISSUE TITLE
Workspace Data > Edit/Update a version or Create a new version

### ISSUE THREAD

**Issue by be-novelt** [WorldHealthOrganization/herams-backend#31]
![9 herams_admin_workspacedata_editupdate](https://user-images.githubusercontent.com/43411015/53990676-19926580-4129-11e9-8d3f-d625fbe33a22.jpg)
![10 herams_admin_workspacedata_editupdate_2](https://user-images.githubusercontent.com/43411015/53990677-19926580-4129-11e9-9045-002efc2d6a4c.jpg)
![11 herams_admin_workspacedata_editupdate_confirm](https://user-images.githubusercontent.com/43411015/53990678-19926580-4129-11e9-99a3-e446b6030340.jpg)
![12 herams_admin_workspacedata_create](https://user-images.githubusercontent.com/43411015/53990680-19926580-4129-11e9-8c58-b4e49097bfd3.jpg)

**Comment by be-novelt** [comment]
Attached the 2 popups which appear when you click on "Edit/Update" or "Create a new version" of a HF (see 6.HeRAMs_admin_WorkspaceData_bis.jpg). The idea is through a simple navigation to integrate this content into the HeRAMs chart, with permanent  buttons (close, cancel, add, create..).

**Comment by SamMousa** [comment]
Screenshots are inconsistent; do we, or do we not show the group name?
The sample page for the *Date* group does not show the group name, whereas others do.
