### ISSUE TITLE
Dashboard maps on staging are not working

### ISSUE THREAD

**Issue by luna404** [WorldHealthOrganization/herams-backend#310]
There seems to be an issue with the dashboard maps on staging. The dashboards themselves work, but maps are either blank or only show a few points,

https://herams-staging.org/project/30
![image](https://user-images.githubusercontent.com/18245059/73842459-e8308700-481c-11ea-89e6-50189dabdcbd.png)

https://herams-staging.org/project/24
![image](https://user-images.githubusercontent.com/18245059/73842349-b0c1da80-481c-11ea-87e3-f3471aad0341.png)

**Comment by luna404** [comment]
That made it even worse :)
Now we get an error for all maps
![image](https://user-images.githubusercontent.com/18245059/73846592-0dc18e80-4825-11ea-9c94-f8b456fd1ed5.png)

https://herams-staging.org/element/631/update
![image](https://user-images.githubusercontent.com/18245059/73846703-41041d80-4825-11ea-8a58-518a3e417c87.png)

**Comment by SamMousa** [comment]
hmm; that's strange; when i go there I get this: 
![image](https://user-images.githubusercontent.com/547021/73847232-21b9c000-4826-11ea-9828-99f013067829.png)

**Comment by SamMousa** [comment]
I have updated the error for dashboard maps to include the response ID, but now the error no longer happens... Let me know if it happens again, then I'll check the individual data that is causing the issue.

**Comment by luna404** [comment]
Thanks, as it's working again. I'll close the issue for now.
