### ISSUE TITLE
Backend administration not working

### ISSUE THREAD

**Issue by luna404** [WorldHealthOrganization/herams-backend#316]
If you click on backend administration on Prod, you are no longer redirected to LS. 

![image](https://user-images.githubusercontent.com/18245059/74146171-d2e2a080-4c00-11ea-98f0-87d01650db84.png)

Access itself is not affected. We can still access LS using the direct url (https://ls.herams.org/admin/survey/sa/index)

**Comment by SamMousa** [comment]
This issue also exists on staging.

**Comment by luna404** [comment]
I get an `Unknown user` error. Tried with my account and Ousmane's.

**Comment by SamMousa** [comment]
That's because your user ID in staging doesn't have a user in LS. I'm gonna guess that it works (the error is an indicator that communication works).
