### ISSUE TITLE
Number of HF shows question mark

### ISSUE THREAD

**Issue by luna404** [WorldHealthOrganization/herams-backend#318]
The total number of health facilities in the carousel displays a question mark instead of the number of HFs.
![image](https://user-images.githubusercontent.com/18245059/74151737-1d6a1a00-4c0d-11ea-8dfd-3ac765d4f92a.png)

**Comment by jeremiehelme** [comment]
@SamMousa This function returns null, 

```
...
    'count' => \Yii::$app->cache->get('totalFacilityCount') ?: '?',
...
```

I guess this is something you put in cache as it requires looping through all the projects.

**Comment by SamMousa** [comment]
It no longer needs to be cached since we have it in a local table, I'll fix it
