### ISSUE TITLE
Impersonate user access needed for HeRAMS Yemen

### ISSUE THREAD

**Issue by JeffDotingco** [WorldHealthOrganization/herams-backend#320]
As discussed in the TC, I will need some support to be provided access to impersonate users for HeRAMS Yemen.

**Comment by SamMousa** [comment]
You can already do that @JeffDotingco, you are global admin.

**Comment by JeffDotingco** [comment]
Thanks @SamMousa for the info. Yes I can see an icon already. thanks!
