### ISSUE TITLE
Survey template / ls / Date questions format

### ISSUE THREAD

**Issue by SamuelPetragallo** [WorldHealthOrganization/herams-backend#322]
Current date format (at least for Yemen) is very unpractictal and confusing.
There's no background on the calendar (so that overalys with other text/elements of the page) and it's generally quite small and unpractical I found

![image](https://user-images.githubusercontent.com/15345099/74233239-9d09ee80-4cca-11ea-9eec-e5089e42ef51.png)

![image](https://user-images.githubusercontent.com/15345099/74233261-a2673900-4cca-11ea-99e4-f3171c6e6a06.png)

**Comment by jeremiehelme** [comment]
I've updated the style for the date picker with the one from the new template. 
It should be better now ?

**Comment by SamuelPetragallo** [comment]
@SamMousa when design is approved like is the case here), shall I remove the tag or add another tag?

**Comment by SamMousa** [comment]
You can replace the tag (i already did) with a tag that starts with `flow:`.

In this case since it is already live (since we only have 1 environment for LS), i'll go ahead and close it.
