### ISSUE TITLE
sign up page not working 

### ISSUE THREAD

**Issue by JeffDotingco** [WorldHealthOrganization/herams-backend#325]
Not working in PROD, but working in STAGING

<img width="1680" alt="Screen Shot 2020-02-13 at 12 20 57 PM" src="https://user-images.githubusercontent.com/50957748/74401163-6ca58a00-4e5b-11ea-96c8-c6130892ae79.png">

**Comment by SamMousa** [comment]
Turns out someone added a trigger to the database outside any normal migrations...
So this change was not in staging which is why we did not catch it...

@JeffDotingco try now!

**Comment by JeffDotingco** [comment]
Thanks!!! @SamMousa. already tested and working now
