### ISSUE TITLE
Error of going to the general settings of HeRAMS YEM (ID:618734)

### ISSUE THREAD

**Issue by JeffDotingco** [WorldHealthOrganization/herams-backend#326]
<img width="1680" alt="Screen Shot 2020-02-13 at 5 04 59 PM" src="https://user-images.githubusercontent.com/50957748/74418365-3da30e80-4e83-11ea-847b-69adf09d8f83.png">

**Comment by JeffDotingco** [comment]
I can only go through the general settings if I deactivate the survey

**Comment by JeffDotingco** [comment]
temporary fix for the time being: deactivate the survey first.

**Comment by SamMousa** [comment]
This will become a bigger issue as data sizes keep increasing.
Should start researching either an upgrade to latest LS, or better, moving away from it.
Especially since fewer people should have access to LS as we move data management & HF management to the platform.

**Comment by SamMousa** [comment]
Can you test this now @JeffDotingco ?

**Comment by JeffDotingco** [comment]
General settings of Yemen working now. thanks @SamMousa
