### ISSUE TITLE
Data export in LS Nigeria doesn't work

### ISSUE THREAD

**Issue by jeremiehelme** [WorldHealthOrganization/herams-backend#327]
Trying to export datas from Nigeria

[Export page](https://ls.herams.org/admin/export/sa/exportresults/surveyid/391149)
[Export error](https://ls.herams.org/admin/export?sa=exportresults&surveyid=391149&statfilter=)

Produce this error 
<img width="1679" alt="Capture d’écran 2020-02-13 à 10 50 22" src="https://user-images.githubusercontent.com/2345926/74422418-dbc8b180-4e4e-11ea-820a-7309f2522030.png">

**Comment by SamMousa** [comment]
Try now, this range of errors is just bad code in LS that is normally hidden.

**Comment by jeremiehelme** [comment]
Yes, working now, thank you !
