### ISSUE TITLE
Token display not working for Conog (#464497)

### ISSUE THREAD

**Issue by luna404** [WorldHealthOrganization/herams-backend#328]
The token display is not working for project (#464497) Congo Brazzaville.

https://ls.herams.org/admin/tokens/sa/browse/surveyid/464497

![image](https://user-images.githubusercontent.com/18245059/74423814-2c410e80-4e51-11ea-9b7e-e4d873764853.png)

**Comment by SamMousa** [comment]
Try now, this range of errors is just bad code in LS that is normally hidden.

**Comment by luna404** [comment]
Cool, it's working again. Thanks!
