### ISSUE TITLE
Service Availability / Overview / Labels of main causes not pulled up in table

### ISSUE THREAD

**Issue by SamuelPetragallo** [WorldHealthOrganization/herams-backend#33]
About the Availability table (priority areas): the label for the main causes are not picked up (guess because it's a compilation of all the causes questions as opposed to pointing out to 1 question only). Ok with me to load labels from the first "causes question" and apply to all (survey design to ensure consistency)

**Comment by SamMousa** [comment]
I think this works if configured correctly:
![image](https://user-images.githubusercontent.com/547021/55152321-6bd70d00-5150-11e9-8aad-75362d816c19.png)
