### ISSUE TITLE
support for error deleting a text display question in LS for HeRAMS YEM  

### ISSUE THREAD

**Issue by JeffDotingco** [WorldHealthOrganization/herams-backend#330]
support for error deleting a text display question in LS for HeRAMS YEM (currently deactivated). Conditions for text display question to be removed already cleared but still receiving an error:

<img width="1680" alt="Screen Shot 2020-02-13 at 7 31 59 PM" src="https://user-images.githubusercontent.com/50957748/74430634-3a664d80-4e98-11ea-8e07-80dd00e7aab2.png">

**Comment by SamMousa** [comment]
Try now, this range of errors is just bad code in LS that is normally hidden.

**Comment by JeffDotingco** [comment]
Thanks @SamMousa, WCO YEM made some modifications again. I am back at questionnaire again before the start of the workshop this Saturday (15 FEB)
