### ISSUE TITLE
Home > improvements

### ISSUE THREAD

**Issue by jeremiehelme** [WorldHealthOrganization/herams-backend#335]
![HeRAMs_map_2bis](https://user-images.githubusercontent.com/2345926/74637755-e646bc00-516a-11ea-8b98-924341f065b6.jpg)

@SamMousa Here is what we discussed last thursday 
- We don't have a profile picture and it's not necessary to add one
We could keep the user sub-menu, that could contain shortcuts (Admin, disconnect, project workspace...)

- Remove partners button for now

**Comment by SamMousa** [comment]
So just remove the picture? Sounds good to me. 
We don't have a partners button anyway and I agree with not adding it, especially in that location.

**Comment by jeremiehelme** [comment]
- Having the admin buttons in the sub menu, where the profile picture is, as well as other shortcuts would be nice
- Having the menu collapsed by default maybe ?

**Comment by SamMousa** [comment]
We just have 2 buttons, I don't see the benefit in collapsing so few items?
![image](https://user-images.githubusercontent.com/547021/74716904-b57c8a80-522f-11ea-8dd8-2006ccc3ecbf.png)

Technically it can be done but all we're doing is adding JS to something that works very well without it.

**Comment by SamMousa** [comment]
Closed in favor of #340
