### ISSUE TITLE
Project Summary > improvements

### ISSUE THREAD

**Issue by jeremiehelme** [WorldHealthOrganization/herams-backend#336]
![Capture d’écran 2020-02-13 à 14 30 39](https://user-images.githubusercontent.com/2345926/74638364-0d51bd80-516c-11ea-8a94-053acd38fdc8.png)
![Capture d’écran 2020-02-13 à 14 33 42](https://user-images.githubusercontent.com/2345926/74638368-0e82ea80-516c-11ea-9bbb-f5f2f140bec6.png)

- Add a shortcut to the workspaces list, next to the dashboard button
- Change the button to "Request access" if we don't have the rights, if possible ?

**Comment by SamMousa** [comment]
> Change the button to "Request access" if we don't have the rights, if possible ?

Yes, makes sense, will need to add a page for that.

> Add a shortcut to the workspaces list, next to the dashboard button

Yes, should be simple enough.

**Comment by SamMousa** [comment]
For now we just do the button to the workspaces list.

**Comment by jeremiehelme** [comment]
added in #287

**Comment by jeremiehelme** [comment]
approved in #287

**Comment by jeremiehelme** [comment]
Closing in favor of Project Summary Popups sizing #208
