### ISSUE TITLE
Password reset not working

### ISSUE THREAD

**Issue by luna404** [WorldHealthOrganization/herams-backend#343]
The password reset button is not working. If you try reset your password, the buttons doesn't seem to work and no email is being sent.

**Comment by luna404** [comment]
This is still an issue. I tried it in Chrome and Firefox, it still doesn't send the link to reset your password.

**Comment by SamMousa** [comment]
![image](https://user-images.githubusercontent.com/547021/75358123-a7271200-58b2-11ea-80cd-907566e99dca.png)

It works, do you get a green popup telling you the message was sent?
If so, check your spam folder.

Just to confirm: you are testing on staging right?

**Comment by luna404** [comment]
Yes I am on staging and no, I don't get green popup.

**Comment by SamMousa** [comment]
Ah, try submitting the form with [enter] instead of clicking the button. 

--> Will fix the button, maybe i tested by using enter.

**Comment by SamMousa** [comment]
Now it should work both when using the [enter] key and when clicking the button

**Comment by luna404** [comment]
I guess it works 

![image](https://user-images.githubusercontent.com/18245059/75360142-b22f7180-58b5-11ea-8c3c-6a83213ed645.png)

**Comment by luna404** [comment]
Is working now

**Comment by JeffDotingco** [comment]
working in PROD

**Comment by JeffDotingco** [comment]
working in PROD
