### ISSUE TITLE
Password change not verifying current password

### ISSUE THREAD

**Issue by luna404** [WorldHealthOrganization/herams-backend#344]
When you change your password, the current password is not being validated. You can enter anything in the first field and then it allows you to change the password :)

![image](https://user-images.githubusercontent.com/18245059/74952766-068fa880-5401-11ea-9dad-26c153610f7b.png)

**Comment by luna404** [comment]
It works, but it would be nice if the users gets a message that password was not updated because the current password was wrong. It's true that you don't get the green pop-up but as the pages changes to the `Profile` tab, it's not clear that the password was not updated.

**Comment by luna404** [comment]
Sorry, I just noticed it does show password incorrect, but because it changes the tab back to `Profile`, you only get it if you go back to the `Password` tab.

**Comment by SamMousa** [comment]
I have updated the flow, if you have an error it takes you to a page that just has the update password tab, so it is immediately obvious.

**Comment by JeffDotingco** [comment]
error when you want to change your current password 
<img width="1680" alt="Screen Shot 2020-02-28 at 10 29 00 PM" src="https://user-images.githubusercontent.com/50957748/75556895-05eab800-5a7a-11ea-92c3-92faa54828c2.png">

**Comment by SamMousa** [comment]
Try now!

**Comment by JeffDotingco** [comment]
working now!
