### ISSUE TITLE
Map / Dot colors

### ISSUE THREAD

**Issue by SamuelPetragallo** [WorldHealthOrganization/herams-backend#35]
Adapt dots colors based on the indicator displayed (green --> red scales for functionality for example - other scales (blues and greys?) for HF types (check with @be-novelt ))

**Comment by SamMousa** [comment]
This is the tool I use to create the scales: https://vis4.net/chromajs/

Any scale given by a design is extended using this tool, in case it does not contain sufficient values.

@SamuelPetragallo I don't think red to green scales are  a good thing. See this article: https://www.vis4.net/blog/2011/11/goodbye-redgreen-scales/

**Comment by SamuelPetragallo** [comment]
I know for the viz discussions around red and green, but they are still part of most people culture and in high demand. For all the "value" scales we have (bad --> good) that's what we need to use

**Comment by SamuelPetragallo** [comment]
Ok on this @SamMousa you've definitely convinced me - can't ignore the barrier this would be to color-blind people + the blue to orange scales do the job quite well still (don't know of there are other replacement scales that you would suggest?)

**Comment by SamMousa** [comment]
Closing since it is being discussed elsewhere.
