### ISSUE TITLE
Backup / Discussion

### ISSUE THREAD

**Issue by SamuelPetragallo** [WorldHealthOrganization/herams-backend#351]
Following the heat wave end of last week on Burkina to discuss reinforcement of backup in general.

Suggestion could be as a start to automate the ls dump once a week as a start: https://ls.herams.org/admin/dumpdb (though it seems more likely that we'll be moving away from it rather sonner than later)

?

**Comment by SamMousa** [comment]
Let's first discuss the goal of these backups in #346.

**Comment by SamuelPetragallo** [comment]
Ah shit had not realized this was already opened... loosing the thread a little today...
