### ISSUE TITLE
Left menu HeRAMS logo

### ISSUE THREAD

**Issue by SamuelPetragallo** [WorldHealthOrganization/herams-backend#353]
Suggest as discussed that we use the horizontal logo instead as we're trying to "slim things down"

**Comment by SamuelPetragallo** [comment]
![HeRAMS_Horizontal_without_baseline_2019](https://user-images.githubusercontent.com/15345099/75249212-167b0400-57d6-11ea-9e6d-c295fc05e02b.png)
[HeRAMS_Horizontal_withoutbaseline.pdf](https://github.com/WorldHealthOrganization/herams-backend/files/4250042/HeRAMS_Horizontal_withoutbaseline.pdf)
![HeRAMS_Horizontal_without_baseline_with_background_2019](https://user-images.githubusercontent.com/15345099/75249213-1844c780-57d6-11ea-8a89-58cd0d138911.png)

**Comment by SamMousa** [comment]
@jeremiehelme There is a vector file in the repo: https://github.com/WorldHealthOrganization/herams-backend/blob/master/public/img/HeRAMS_NGA.svg

Please use that to create a SVG horizontal logo; that way we get the best quality.
