### ISSUE TITLE
Add workspace name to data export

### ISSUE THREAD

**Issue by luna404** [WorldHealthOrganization/herams-backend#354]
When exporting the data, the workspace name should be included as part of the system variables.

**Comment by SamMousa** [comment]
During the call you mentioned the workspace ID... I have added the ID on staging.

**Comment by luna404** [comment]
Yes I did say workspace id, but I realized that this will not mean much to users. Could we use the same logic as for questions? If a users selects to export as code it exports the workspace ID and if they choose to export as text it exports the workspace name?

**Comment by SamMousa** [comment]
@luna404 as far as I can tell this is already on prod.
Could you confirm that it works as expected, and if so, close this?

**Comment by luna404** [comment]
Works on both staging and production
