### ISSUE TITLE
Data cache/refresh 

### ISSUE THREAD

**Issue by luna404** [WorldHealthOrganization/herams-backend#357]
I'm creating a new issue to summarize issues related to the data cache/refresh.

I did some testing on both staging and production. @JeffDotingco can you think of any other scenario that I might have forgotten?

|  	| Staging 	| Prod 	| Comment 	|
|-----------------------	|-------------	|-------------	|------------------------	|
| Create new record 	| Works 	| **Not working** 	|  	|
| Edit record 	| Works 	| **Not working** 	|  	|
| Save and resume later 	| **Not working** 	| **Not working** 	|  	|
| Delete record 	| Works 	| **Not working** 	|  	|
| Import Workspace 	| **Not working** 	| **Not working** 	| Related to issue #332  	|

**Comment by SamMousa** [comment]
Save & resume later is not part of the flow, never has been. The method was that people had to go to the last page and submit there.

**Comment by SamMousa** [comment]
Import workspace also was never part of the flow for syncing automatically; so based on that we can conclude that everyhing works on staging.

**Comment by SamMousa** [comment]
Since this is part of the current staging environment it should work when we release.
