### ISSUE TITLE
Map / Service availability / Aggregate measure

### ISSUE THREAD

**Issue by SamuelPetragallo** [WorldHealthOrganization/herams-backend#36]
Maps in service availability to display an aggregate measure of availability: % of fully available ranked from 0-25; 25-50; 50-75; 75-100% available (red to green) + legend

**Comment by SamMousa** [comment]
![image](https://user-images.githubusercontent.com/547021/63434115-bd947280-c424-11e9-88b2-4ff34f15122c.png)

Took a while, but we got it!
