### ISSUE TITLE
Hide report date by default

### ISSUE THREAD

**Issue by luna404** [WorldHealthOrganization/herams-backend#362]
Issue related to #359 and #347 

By default users should always export all data. Thus, the `Report date` field should not be shown unless the user specifies to restrict the export. 

- [ ] Add question "Export all records". Default value should be "Yes" 
- [ ] Report date should only be shown if the users changes the "Export all records" question to no.

**Comment by SamMousa** [comment]
@SamuelPetragallo one of your requirements was that there are not a lot of clicks required to get this functionality.

Furthermore hiding functionality behind checkboxes makes it less intuitive for everyone involved, both code and user experience.

If we really need to hide it we could do something like a collapsible widget with advanced settings.


![image](https://user-images.githubusercontent.com/547021/75888191-4ad06f00-5e2b-11ea-9ca3-593470c7faaf.png)

**Comment by SamMousa** [comment]
![image](https://user-images.githubusercontent.com/547021/75888241-59b72180-5e2b-11ea-946c-5a182e1dfc49.png)

**Comment by SamMousa** [comment]
This can now be previewed in project/export:
https://www.herams-staging.org/project/30/export

**Comment by luna404** [comment]
This is very nice! Can we use the same design for workspace export?

**Comment by SamMousa** [comment]
Yes. will add that for tomorrows' release
