### ISSUE TITLE
Worldmp / Project popup / Type

### ISSUE THREAD

**Issue by SamuelPetragallo** [WorldHealthOrganization/herams-backend#37]
The first pie to be titled "Type" (vs. "Functionality")

**Comment by SamuelPetragallo** [comment]
Type labels are still incorrect (not sure if that's down to me/config or not)

**Comment by SamMousa** [comment]
Screenshot?

**Comment by SamuelPetragallo** [comment]
It was configurable. Have managed to update A1 and A2 but subsequent categories are not taken into account (syntax is "A1": "Tertiary","A2": "Secondary","A3": "Primary","A4": "Primary","A5": "Primary","A6": "Primary","A7": "Mobile" - only A1 and A2 are displayed, others fall under unknown)
