### ISSUE TITLE
Design error page

### ISSUE THREAD

**Issue by SamMousa** [WorldHealthOrganization/herams-backend#41]
@SamuelPetragallo  does it make sense to ask Bruno for an error page as well?

We need one to fit in nicely with the rest of the design.

**Comment by SamuelPetragallo** [comment]
Yes definitely. Bruno, do you copy us here? (can't find you when using the @)

**Comment by SamMousa** [comment]
@be-novelt

**Comment by be-novelt** [comment]
Hi,
what do you think of this page? 
Can we display informations like Project, HF or Contributors?
![Herams_ErrorPage](https://user-images.githubusercontent.com/43411015/54600449-19ee0300-4a3d-11e9-87ac-51ea003b503c.jpg)

**Comment by SamMousa** [comment]
I'd advice to just have the go home button. Browsers have a back button that users will know how to find anyway.

**Comment by SamuelPetragallo** [comment]
Ok we had some discussion with Bruno taking your comment into account - we'll keep both links but simply remove the text around them "Back" and "Home".

A question for me: what about pages a user does not have access to? I guess the user will simply not see them or have the option to request access when available (vs. getting an error message) - but just making sure - ?

**Comment by be-novelt** [comment]
![Herams_ErrorPage_1](https://user-images.githubusercontent.com/43411015/54628550-12971b80-4a76-11e9-8380-f1d8cb7d5bbf.jpg)
![Herams_ErrorPage_2](https://user-images.githubusercontent.com/43411015/54628551-12971b80-4a76-11e9-8904-ca5a06268915.jpg)

**Comment by be-novelt** [comment]
Attached a proposition of Error page and Access denied. What do you think about it?

**Comment by SamMousa** [comment]
I like  the request access button and the home button. The back button I don't like since it will have weird behavior for things like filled forms or redirects leading to errors.

**Comment by SamuelPetragallo** [comment]
That's great Bruno thanks! Sam, understood for the potential loop holes using a "Back" button. I'm ok removing that for now, but in this case I find it strange to only be offered "Home"... I know the end result would be the same and hence it's not a necessarily a great thing, but what about a "Close" button then instead (than would behave as Home)?

**Comment by SamMousa** [comment]
![image](https://user-images.githubusercontent.com/547021/55220775-502f3d80-5208-11e9-8503-dcbee21249df.png)


First draft. See https://herams-staging.org/this-does-not-work
