### ISSUE TITLE
Named colors

### ISSUE THREAD

**Issue by SamMousa** [WorldHealthOrganization/herams-backend#42]
Currently we use a lot of colors and we all refer to them by their color code (for example `#42424b`).

In most designs, the same color keeps coming back, and it makes sense to give these colors a name.

For example we could define the color above as `dark-background-color`. The advantage of naming these colors are several:
1. It allows me to pick a "decent" placeholder from the available colors in the palette of the design.
2. Changing a color in the palette changes all uses of that color, making it an easier investment.
3. Allows experimenting with different color sets directly in the browser.

Currently I cannot know if 2 elements should always be the same color, or if they just currently happen to have the same color; ie. if one of them needs to be changed, do I need to change the other?

**Comment by be-novelt** [comment]
Ok, I see, I ll try to give you this color range. And I should send you today the icons in svg.

**Comment by SamMousa** [comment]
> And I should send you today the icons in svg.

Any update on the ETA for these?

**Comment by SamMousa** [comment]
@be-novelt ?
