### ISSUE TITLE
Move "Partners icon" (the one below the HeRAMS logo op left) to bottom left

### ISSUE THREAD

**Issue by SamuelPetragallo** [WorldHealthOrganization/herams-backend#44]
Yes, this is following our discussion to make the overall design more flexible for mobile etc. and specifically about moving the icon pointing to the list of Partners (which in Bruno's last mockups was place in the small round icon below the HeRAMS logo top left of the page) and integrating it  in the bottom left space / so "Partners" becomes one of the strolling pieces of information together with # Projects, # HFs and # Contributors

**Comment by SamMousa** [comment]
Details please
