### ISSUE TITLE
Users list actions: "envelope icon" returns a strange message

### ISSUE THREAD

**Issue by SamuelPetragallo** [WorldHealthOrganization/herams-backend#51]
Image removed.

**Comment by SamMousa** [comment]
Hovering over the icon shows you what it will do:
![image](https://user-images.githubusercontent.com/547021/55151407-7beded00-514e-11e9-9fa7-858b3295697b.png)


The weird message is simply asking for confirmation executing the action.

Also: check your screenshots for sensitive information before posting them, this is all public!
