### ISSUE TITLE
Unequal access to Project Management actions

### ISSUE THREAD

**Issue by SamuelPetragallo** [WorldHealthOrganization/herams-backend#52]
CAR is the only project I can delete (see below). Guess it's due to the fact that you originated the other ones. Just pointing out we need to look at these permissions and clarify

![image](https://user-images.githubusercontent.com/15345099/54769890-73ebf580-4c02-11e9-9be7-8f3b8cfa9b29.png)

**Comment by SamMousa** [comment]
Projects cannot be deleted when they have workspaces.
