### ISSUE TITLE
Implement Bruno's icons

### ISSUE THREAD

**Issue by SamuelPetragallo** [WorldHealthOrganization/herams-backend#53]
... for those that are available (admin, logout?)

**Comment by SamMousa** [comment]
Have not received any of them yet.

**Comment by be-novelt** [comment]
Hi Sam, I sent them by email, but maybe your address was wrong, sorry... so see attached the last icons in svg >>
[Icons.zip](https://github.com/WorldHealthOrganization/herams-backend/files/2993940/Icons.zip)

**Comment by SamuelPetragallo** [comment]
Thanks Bruno! I'm drawning in my emails these days... good to have them here now thanks!

**Comment by SamMousa** [comment]
Thanks, works for me.

**Comment by SamuelPetragallo** [comment]
No prob them - will discover it on UAT :)

**Comment by SamMousa** [comment]
Fixed this for most icons, some things still on the to do, like menus.

**Comment by SamMousa** [comment]
@SamuelPetragallo I recommend putting the rest in next milestone.

**Comment by SamuelPetragallo** [comment]
Could maybe be completed for the upcoming release?

**Comment by SamMousa** [comment]
Don't have all of them yet
