### ISSUE TITLE
(Mis?)configuration of HF type returned a error (Sudan here)

### ISSUE THREAD

**Issue by SamuelPetragallo** [WorldHealthOrganization/herams-backend#55]
![image](https://user-images.githubusercontent.com/15345099/54954632-66f53c00-4f4b-11e9-82ce-8e09b2809c72.png)

**Comment by SamMousa** [comment]
The screenshot d oesnt show an error

**Comment by SamuelPetragallo** [comment]
Seems to work now - not sure what happened - closed

**Comment by SamuelPetragallo** [comment]
All good
