### ISSUE TITLE
New project (Ethiopia) created successfully / Project popup breaks

### ISSUE THREAD

**Issue by SamuelPetragallo** [WorldHealthOrganization/herams-backend#56]
![image](https://user-images.githubusercontent.com/15345099/54955351-547c0200-4f4d-11e9-9191-d737d38fdd9f.png)

**Comment by SamuelPetragallo** [comment]
Same for Philippines

**Comment by SamMousa** [comment]
The survey for Ethiopia is invalid.
At least one question: `QHeRAMS427` satisfies the agreed upon definition of a service, but it is not a service.

**Comment by SamuelPetragallo** [comment]
Yes, found out a numbre of numeric field questions there. Removed all!
Still not loading but assume it is now only dependant on #62
