### ISSUE TITLE
Manual refresh of HeRAMS data

### ISSUE THREAD

**Issue by SamuelPetragallo** [WorldHealthOrganization/herams-backend#6]
Possibility for users to manually force data refresh, vs waiting on the 1h automated refresh.
To be discussed with Bruno as well maybe

**Comment by SamuelPetragallo** [comment]
Possibility for users to manually force data refresh, vs waiting on the 1h automated refresh.
To be discussed with Bruno as well maybe

**Comment by SamMousa** [comment]
This issue has been resolved via automatic cache warmup.
