### ISSUE TITLE
Chad's baseline dates in ls are funky

### ISSUE THREAD

**Issue by SamuelPetragallo** [WorldHealthOrganization/herams-backend#60]
![image](https://user-images.githubusercontent.com/15345099/55030230-32958480-500c-11e9-8c1a-edef00b917e9.png)

**Comment by SamuelPetragallo** [comment]
In case that implies re-importing, please let me know, I have done some more cleaning of the baseline here with the guys, if not no problem, it will be re-cleaned online

**Comment by SamMousa** [comment]
Can just export current data and so a global replace, should be simple.

**Comment by SamMousa** [comment]
Set them to 2019.
