### ISSUE TITLE
Chad -Map out Health Facility Type and Functionality to the worldmap popup

### ISSUE THREAD

**Issue by SamuelPetragallo** [WorldHealthOrganization/herams-backend#62]
Health Facility Type : MoSD3
Functionality: HFFUNCT

Also ideally Service Availability is greyed out (and no legend shown) as there's no data (if easily/quickly implemented)

**Comment by SamMousa** [comment]
This changes breaks functionality for all other projects.

**Comment by SamuelPetragallo** [comment]
Not sure what the issue is here and what can be done

**Comment by SamMousa** [comment]
It works, you need to test it on staging, and realize that when we deploy this other stuff breaks unless we update all surveys

**Comment by SamMousa** [comment]
All elements that reference those code will need updating, I am doing this at the moment.

**Comment by SamMousa** [comment]
Have also made the reporting a bit more robust, so that when it fails it at least allows you to recover...
![image](https://user-images.githubusercontent.com/547021/55148723-0c293380-5149-11e9-8107-e0dde8f0afee.png)

**Comment by SamMousa** [comment]
Chad still had GPS coordinates in the wrong questions, as well as bad delimiters and sometimes bad delimiters.
