### ISSUE TITLE
Chad Project Dashboard / Setup first page

### ISSUE THREAD

**Issue by SamuelPetragallo** [WorldHealthOrganization/herams-backend#63]
For now just the Overview with

1. Map with HF Type (MoSD3)  (as in all projects)
2. Graph with functionality
3. Priority table on functionality (per district, the second level displayed in GEO1)

**Comment by SamMousa** [comment]
The agreed upon standard was that each HeRAMS response would have type of facility in HF2... :-/

**Comment by SamMousa** [comment]
The priority table cannot yet be configured to take the data this way. The rest has been configured on staging:
![image](https://user-images.githubusercontent.com/547021/55087629-ad14e180-50aa-11e9-9b3c-331b79fabfb9.png)

**Comment by SamuelPetragallo** [comment]
Huge thanks Sam!
