### ISSUE TITLE
User list in admin doesn't load

### ISSUE THREAD

**Issue by SamuelPetragallo** [WorldHealthOrganization/herams-backend#65]
This page: https://ls.herams.org/admin/usergroups/sa/index

![image](https://user-images.githubusercontent.com/15345099/55092636-2dd7db80-50b3-11e9-9849-0297324176d8.png)

**Comment by SamMousa** [comment]
Doesn't look like an error to me. There are probably no user groups in LS that you have access to.

**Comment by SamuelPetragallo** [comment]
I was trying to access users list - my bad
