### ISSUE TITLE
Staging / Access to NGA project returns an error

### ISSUE THREAD

**Issue by SamuelPetragallo** [WorldHealthOrganization/herams-backend#66]
![image](https://user-images.githubusercontent.com/15345099/55092868-a5a60600-50b3-11e9-9ac2-62cb53dc86d8.png)

**Comment by SamMousa** [comment]
Yes, since we are moving to Chad standard.

**Comment by SamuelPetragallo** [comment]
Ok - can I change question codes in NGA then? in ls?

**Comment by SamuelPetragallo** [comment]
Sam I fucked up with Chad - it's MoSDGPS - sorry Sam

**Comment by SamMousa** [comment]
It currently works for chad though

**Comment by SamMousa** [comment]
I can change it to whatever you prefer, or we make it configurable per project

**Comment by SamuelPetragallo** [comment]
Yes cause I fucked up for Chad and used the wrong one 👎 ... I've changed now (they have eaten my brains today...)

**Comment by SamMousa** [comment]
So what codes do I use?
