### ISSUE TITLE
LS template tweak

### ISSUE THREAD

**Issue by SamuelPetragallo** [WorldHealthOrganization/herams-backend#69]
- remove HeRAMS logo (duplicated now that it shows in a frame)
- remove survey title
- apply standard blue color to survey title

**Comment by SamMousa** [comment]
Seems 2 and 3 contradict..

**Comment by SamuelPetragallo** [comment]
That's heart warming dude :)... 2 is survey title / 3 is the question group title

**Comment by SamMousa** [comment]
:-D

**Comment by SamuelPetragallo** [comment]
Felt less lonely for a while... :D

**Comment by SamuelPetragallo** [comment]
That would be nice for this am as quite minor

**Comment by SamMousa** [comment]
Removed title and logo.

**Comment by SamuelPetragallo** [comment]
That's what I was talking about - did we miss out on this?

![image](https://user-images.githubusercontent.com/15345099/55221261-58d44380-5209-11e9-9f06-4df7be684cbe.png)

**Comment by SamMousa** [comment]
Ah, I thought you were talking about admin part, not the participant stuff. (Those were always inside HeRAMS with the double logo). I'll remove those as well.
