### ISSUE TITLE
Can not add french as additional site language in ls (global settings)

### ISSUE THREAD

**Issue by SamuelPetragallo** [WorldHealthOrganization/herams-backend#70]
![image](https://user-images.githubusercontent.com/15345099/55107058-ac8f4180-50d0-11e9-8e2d-b81f46e2ec11.png)

**Comment by SamMousa** [comment]
Not sure what the goal is, in global settings all languages are currently enabled.
Moving them to the right means disabling them.

**Comment by SamuelPetragallo** [comment]
Hmmm ok - may bad - how can users switch from one to the other? French and Arabic are quite strong here

**Comment by SamuelPetragallo** [comment]
Finally found where individual users can pick their preferred language
