### ISSUE TITLE
Footer improvements

### ISSUE THREAD

**Issue by SamMousa** [WorldHealthOrganization/herams-backend#74]
- [ ] Extract code into widget
- [x] Show project that was last updated (currently it shows a random project and a random number of hours since last update)
- [x] Identify metrics to show so we can scroll through
- [x] Implement switching between metrics, via a timer as well as user initiated.

**Comment by SamMousa** [comment]
The footer should automatically show the next metric every 5 seconds.
Manually switching metrics resets the counter.

Mark this issue as ready if functionality is correct.
Create new issues for each new metric desired.

**Comment by SamuelPetragallo** [comment]
Scrolling works fine - there's however a discrepancy between the metrics shown here and the same metrics on the pre-login page - will open another issue for that
