### ISSUE TITLE
WS results table / column headers no longer truncate ls labels to ":"

### ISSUE THREAD

**Issue by SamuelPetragallo** [WorldHealthOrganization/herams-backend#76]
See Update or MoSD below

![image](https://user-images.githubusercontent.com/15345099/55176040-ac4e7f00-5180-11e9-9472-27aa33563aa0.png)

**Comment by SamMousa** [comment]
Nothing has changed in the plugin..

**Comment by SamuelPetragallo** [comment]
Was that already the case? I thought these were truncated on arrival in herams for all further use

**Comment by SamuelPetragallo** [comment]
Same, would need post presentation to get started with the team here

**Comment by SamMousa** [comment]
The plugin doesn't do truncating, instead it allows you to specify the title to use in its configuration:
```
Update:text
GEO1:select
MoSD2:text:MoSD Name
MoSD3:select
HFFUNCT:select:Functionalité
```
