### ISSUE TITLE
WS results table / answer text no longer pulled up

### ISSUE THREAD

**Issue by SamuelPetragallo** [WorldHealthOrganization/herams-backend#77]
![image](https://user-images.githubusercontent.com/15345099/55176153-e3bd2b80-5180-11e9-80fe-5ce50233f85b.png)

**Comment by SamuelPetragallo** [comment]
Thought it was to do with config of plugin but seems it's unrelated.

**Comment by SamMousa** [comment]
It is definitely a plugin issue

**Comment by SamuelPetragallo** [comment]
That would be needed for morning post-presentation as I should start working with colleagues here ;)

**Comment by SamuelPetragallo** [comment]
That's I would need post presentation to get started with the team here

**Comment by SamMousa** [comment]
Probably caused because there is no english version available.

**Comment by SamMousa** [comment]
Fixed, it happens because LS is buggy as usual. In this case the start language of the responses was not set causing it to not map data correctly. I have exported + reimported data and set startlanguage to french for every response.
