### ISSUE TITLE
Map colors change after filter is applied (color matching seems to reset to the remaining values / not fixed to a given ls answer code)

### ISSUE THREAD

**Issue by SamuelPetragallo** [WorldHealthOrganization/herams-backend#80]
![image](https://user-images.githubusercontent.com/15345099/55178189-3567b500-5185-11e9-913d-936ee80c1665.png)

![image](https://user-images.githubusercontent.com/15345099/55179019-e9b60b00-5186-11e9-820a-e0514565f7c3.png)

**Comment by SamMousa** [comment]
I think you can specify colors as a map instead of array. That way you can specify the color / answer code connection.

```
"colors": {
"A1": "blue",
"A2": "red"
}
```
Let me know if that works.

**Comment by SamuelPetragallo** [comment]
Tried that. it did not return an error, but nothing shows on the map 

{
    "code": "HFFUNCT",
    "colors": {
        "A1": "rgb(46, 204, 113)",
        "A2": "rgb(242, 38, 19)",
        "A3": "rgb(189, 195, 199)"
    }
}

**Comment by SamuelPetragallo** [comment]
Unfortunately got an error in return... but an idea to explore as more robust (unless we can have the options diplayed and simply aligne colors... but that's for later I guess... :p )
