### ISSUE TITLE
Charts don't seem to pick up the right colours

### ISSUE THREAD

**Issue by SamuelPetragallo** [WorldHealthOrganization/herams-backend#81]
![image](https://user-images.githubusercontent.com/15345099/55180150-4b777480-5189-11e9-86a5-e8b91b913bc4.png)

**Comment by SamMousa** [comment]
They do, but the unknown value color is added. You can disable or change that with another setting (check some other chart configs)

**Comment by SamuelPetragallo** [comment]
Found the     "notRelevantColor": null (thumbs)
