### ISSUE TITLE
Nigeria / data refresh?

### ISSUE THREAD

**Issue by SamuelPetragallo** [WorldHealthOrganization/herams-backend#84]
Cleaned all geo outliers in Nigeria. Data seems not to have refreshed

**Comment by SamuelPetragallo** [comment]
Hmmm stranger - seems to have refreshed on my phone (at least to lat/long 0/0 and quite a few of the asia based ones are gone), but still not on pc despite cache clear, etc.

**Comment by SamMousa** [comment]
In the project overview you can see the cache status, it should never go (much) over 30 minutes.
![image](https://user-images.githubusercontent.com/547021/55217178-26bde400-51ff-11e9-989e-bb3cf3d49067.png)
