### ISSUE TITLE
LS - template of printable forms still has the Prime logo

### ISSUE THREAD

**Issue by SamuelPetragallo** [WorldHealthOrganization/herams-backend#85]
https://ls.herams.org/admin/printablesurvey/sa/index/surveyid/954572/lang/fr

Great if that could be removed and replaced with the flat HeRAMS logo (will ping Bruno to share that one as I can't access my share drives from here)

Great to have tomorrow COB so that forms taken to the field are labelled properly

**Comment by SamMousa** [comment]
COB?

**Comment by SamMousa** [comment]
Fixed via the LS template editor.
